kyma-project/api-gateway

- Makefile
- README.md
- config/default/manager_args_patch.yaml
- config/default/manager_args_patch.yaml.tmpl
- controllers/apirule_controller.go
- internal/processing/processing.go
- internal/processing/processing_test.go
- main.go
- Remove JWKS uri from parameters as it was not used
**Reasons**
https://github.com/kyma-project/kyma/blob/4ed4d5883dcedf6470d86ba6c273e0dfdeaed589/resources/api-gateway/values.yaml#L28
> Remove JWKS-URI in API-gateway

- .goreleaser.yaml
> Add https to image urls

- Makefile
> Restore docker build and push on PR

- internal/processing/processing.go
- Look for resources by v1alpha1 label
> Look for v1alpha1 resources by label

- internal/processing/processing.go
- internal/processing/processing_test.go
- Cherrypick label fetching by v1alpha1 label fix
- https://github.com/kyma-project/api-gateway/issues/32
> Cherrypick changes from label fetching fix

- api/v1beta1/apirule_types.go
- config/crd/bases/gateway.kyma-project.io_apirules.yaml
- https://github.com/kyma-project/api-gateway/issues/52
> Add additional columns when listing API Rules on the cluster

- .github/ISSUE_TEMPLATE/feature_request.md
Adding DoD to the issue template
> Adding DoD to the issue template

- .github/dependabot.yml
- .github/pull-request-template.md
- Add dependabot configuration
- Fix broken link to licence agreements documentation
See #56
> Dependabot config

- internal/helpers/config.go
- Change the path so mount can be performed on subpath
> Update path for api-gateway conf

- config/manager/manager.yaml
> Update volume mount path

- hack/oathkeeper.ory.sh_rules.yaml
- Print handler when listing Ory Rules
- Print scope for OAuth2
> Print handler for Ory Rule

- controllers/suite_test.go
- internal/builders/builders_suite_test.go
- internal/processing/processing_test.go
- internal/validation/validate_test.go
> Add prow reporter

- docs/feature-toggle.md
- Adds internal documentation about how to configure JWT feature toggle
https://github.com/kyma-project/api-gateway/issues/40
> Add JWT handler internal docs in component

- .github/dependabot.yml
-  Add Dependabot config to create patch PR's to release-1.1
> Configure Dependabot for release-1.1

- internal/processing/istio/jwt_validator.go
- internal/processing/ory/jwt_validator.go
- Add comment about jwt to istio handler branch
> Add comment regarding iss jwt claim validation

- internal/builders/istio.go
- internal/processing/istio/authorization_policy_processor.go
- internal/processing/istio/authorization_policy_processor_test.go
- Add specific Principals to From on allow and ory AccessStrategies
- https://github.com/kyma-project/api-gateway/issues/75
> Add principals to Ory/allow APs

- Makefile
- controllers/apirule_controller.go
- internal/processing/istio/jwt_validator.go
- internal/processing/istio/jwt_validator_test.go
- internal/processing/ory/jwt_validator.go
- internal/processing/ory/jwt_validator_test.go
- internal/validation/validate.go
- Run reconcilation periodically (set to 30 minutes)
- If reconcilation reports conflict run the reconcilation faster
- Don't re-reconcile ConfigMap
- https://github.com/kyma-project/kyma/issues/10146
> Run reconcilation periodically

- controllers/api_controlller_reconciliation_test/api_controller_integration_test.go
- controllers/api_controlller_reconciliation_test/suite_test.go
- controllers/apirule_controller.go
- internal/processing/istio/jwt_validator.go
- internal/processing/istio/jwt_validator_test.go
- internal/processing/ory/jwt_validator.go
- internal/processing/ory/jwt_validator_test.go
- internal/validation/validate.go
- main.go
- Cherrypick periodic reconciliation
> Cherrypick periodic reconciliation to rel 1.2

- .github/dependabot.yml
- Update dependabot config to use release 1.2
> Update dependabot.yml for release 1.2

- .github/dependabot.yml
> Bump to 1.3

- docs/istio-jwt.md
- Add documentation regarding Istio JWT aud claim configuration
- https://github.com/kyma-project/api-gateway/issues/178
> Update istio-jwt docs with AUD

- controllers/api_controller_integration_test.go
- controllers/apirule_controller_status_integration_test.go
- controllers/reconciliation_test/api_controller_integration_test.go
- controllers/suite_test.go
- Add eventually assertions to reduce flakiness of integration tests
> Reduce flakiness of integration tests

- Makefile
- hack/kyma-components.yaml
- main.go
- tests/integration/main_test.go
- tests/integration/pkg/helpers/helpers.go
- Add new commands to Makefile
- Remove print for potential leak of credentials
> Add installation of Kyma and provisioning k3d to Makefile

- controllers/apirule_controller_validation_integration_test.go
- go.work.sum
- internal/processing/istio/jwt_validator.go
- internal/processing/istio/jwt_validator_test.go
- internal/validation/authorizations_validation.go
- Fix validation of JWT Istio handler audiences to match the behaviour of requiredScopes and ACs
- Fix possible nil panic in api-gateway when an empty authorization is defined
- Fix validation of JWT Istio handler requiredScope so it's optional as expected in [initial issue](https://github.com/kyma-project/api-gateway/issues/148)
- https://github.com/kyma-project/api-gateway/issues/178
> Audiences validation

- tests/integration/features/istio-jwt/Istio_jwt_two_strategies.feature
- tests/integration/features/istio-jwt/istio_jwt.feature
- tests/integration/manifests/istio-jwt-audiences.yaml
- Add missing test verifying OR support for audiences
> Add test audiences integration test

- tests/integration/scenario_audience_test.go
- Add missing step for audience integration step so that it won't be skipped any more
> Add missing step for audience integration test

- tests/integration/scripts/jobguard/run.sh
- Fix job guard when waiting on build/image-push when running on main branch
> Fix jobguard for when waiting on main branch

- Makefile
- Change image version format for built image on post-submit
> Image version format for built image on post-submit

- Makefile
> Post image version

- docs/mutators/id-token-envoyfilter/.helmignore
- docs/mutators/id-token-envoyfilter/Chart.yaml
- docs/mutators/id-token-envoyfilter/files/filter.lua
- docs/mutators/id-token-envoyfilter/templates/06-support-for-mutators.yaml
- docs/mutators/istio-mutators-support.md
- Add mutators support docs
- https://github.com/kyma-project/api-gateway/issues/212
> Add documentation about Ory mutators support with Istio

- Dockerfile
- go.mod
> Update GO to 1.20.2

- Dockerfile
- go.mod
- Cherrypick https://github.com/kyma-project/api-gateway/commit/ea1b79aa2ddb55088d7c14ade9f1c3364a02efb4
> Update GO to 1.20.2 (#258)

- Makefile
- controllers/api_controller_integration_test.go
- integration tests more expressive and increase stability
> Make integration tests more expressive and increase stability

- .goreleaser.yaml
- Change registry from `eu.gcr.io/kyma-project` to `europe-docker.pkg.dev/kyma-project/prod`
> Adapt api-gateway-controller registry

- Makefile
- Update config used by integration job to install components, so it can find the PR build
> Use new image registry

- docs/istio-jwt.md
> Add info about requestPrincipals creation

- docs/istio-jwt.md
- Update docs for `tokenFrom` JWT feature
> Update docs for tokenFrom JWT feature

- .github/ISSUE_TEMPLATE/adr.md
> Create adr.md issue template

- tests/integration/README.md
- Bring changes from https://github.com/kyma-project/kyma/pull/17360
> Custom domain tests updates

- docs/api-rule-cr.md
- Add mandatory info and specific validation rules to Istio JWT access strategy configuration
- https://github.com/kyma-project/api-gateway/issues/314
> Jwt mandatory doc

- controllers/api_controller_integration_test.go
- controllers/api_controller_test.go
- controllers/apirule_controller.go
- controllers/apirule_controller_status_integration_test.go
- controllers/apirule_controller_validation_integration_test.go
- controllers/suite_test.go
- controllers/types.go
- internal/processing/istio/authorization_policy_processor.go
- main.go
- Restructure Initialisation of ApiGatewayReconciler so we are using the implementation used in production for our tests
- Add tests for `[Istio JWT] Chaos testing`
- Add tests for `API Gateway expose reserved domain`
> Add Integration tests

- hack/release.sh
/area ci
/kind feature
Adjust script to run jobguard that waits for integration jobs, run goreleaser and release It's meant to use only in `rel-api-gateway-goreleaser`.
> reuse release.sh script to wait on other jobs

- .github/ISSUE_TEMPLATE/adr.md
- .github/ISSUE_TEMPLATE/feature_request.md
Add information that codeowner has to verify code coverage for newly added feature.
> Update issue templates

- docs/jwt-ory-to-istio.md
- Add documentation about Istio breaking changes
> Add breaking changes documentation to api-gateway repo

- internal/builders/istio.go
- internal/builders/istio_test.go
- change istio's JWTRule forwardOriginalToken property to true
- add unit tests related to the change
> Add forwardOriginalToken true to istio's JWTRule

- tests/integration/main_test.go
- Enable godog strict mode to fail the run on pending or skipped steps
> Enable godog Strict mode

- controllers/apirule_controller.go
- internal/helpers/common.go
- internal/processing/istio/jwt_validator.go
- internal/processing/istio/jwt_validator_test.go
- internal/validation/validate.go
- internal/validation/validate_test.go
- Move label selector validation to Istio JWT
> Validate label selector only in Istio JWT

- controllers/apirule_controller.go
- internal/helpers/common.go
- internal/processing/istio/jwt_validator.go
- internal/processing/istio/jwt_validator_test.go
- internal/validation/validate.go
- internal/validation/validate_test.go
- Cherrypick https://github.com/kyma-project/api-gateway/commit/2f0a03f52b51aeaba466719484e2e780b552d789
> Fix label selectors validation in 1.7 release

- hack/release.sh
> Wait only for build jobs on release

- tests/integration/pkg/manifestprocessor/processor.go
- Refactor manifests gathering
> Refactor manifests gathering

- tests/integration/testsuites/custom-domain/manifests/resources.yaml
- Remove `---` at the end of `resources.yaml`
> Fix yaml for resources

- .github/dependabot.yml
…elease
- Update dependabot release branch config, because it'S still using old release branch
> Update release-branch in dependabot

- Makefile
- tests/integration/scripts/test-gardener-aws.sh
- tests/integration/scripts/test-gardener.sh
- Increase timeout for install-kyma make target
> Change integration tests config for aws

- .github/dependabot.yml
> Add grouping for Kubernetes PRs in Dependabot

- config/configmap/configmap.yaml
- config/configmap/kustomization.yaml
- config/default/kustomization.yaml
- controllers/gateway/suite_test.go
- controllers/operator/apigateway_controller_integration_test.go
- controllers/operator/suite_test.go
- Remove api-gateway-config  to avoid that lifecycle-manager will reconcile.
- Add first testenv integration test for API Gateway controller
- https://github.com/kyma-project/api-gateway/issues/474
> Remove api-gateway-config cm

- Makefile
- hack/kyma-components.yaml
- kyma-install was removed during module introduction, but for testing capabilities we need to keep this. At some point this should be replaced with capabilities to install istio module.
- https://github.com/kyma-project/api-gateway/issues/474
> Add kyma-install again

- Makefile
- hack/build_and_push_locally.sh
- hack/download_module_image.sh
- script allowing to build and push module and binary image locally (e.g. k3d registry)
- script allowing to download module image to local directory (and inspect the contents later on)
> Makefile adjustments and helper scripts

- .github/workflows/create-release.yaml
- scripts/create_changelog.sh
- scripts/create_draft_release.sh
- scripts/publish_assets.sh
- scripts/publish_release.sh
- Release workflow (on dispatch)
- helper shell scripts
> Release on mod-dev: initial workflow and scripts

- internal/helpers/common.go
- Trigger manager image build on new post job to have sec scanner setup possible
> Trigger manager image build

- .github/actions/wait-for-job-succeed-or-fail/action.yaml
- .github/workflows/integration-tests.yaml
- Use pull ref for status fetch
> Fix integration test pipeline #2

- docs/release-notes/0.0.1-dev.md
> Stub of release-notes for testing purposes

- Makefile
- tests/integration/scripts/jobguard.sh
- Use jobguard defined in PATH instead of from direct path
> Use jobguard from path

- .github/workflows/main-integration.yaml
- Add workflow dispatch for main integration workflow
> Add workflow dispatch for main integration workflow

- Makefile
- hack/ci/Makefile
- scripts/create_draft_release.sh
- echo commands without invalid parameter `-e`
- no progress shown for curl downloading kyma CLI
- more messages
> Typos, messages and  improvements regarding module building

- Makefile
- hack/ci/Makefile
- sed invocation corrected
- additional target added to get the latest release version: `get-latest-release`
> sed corrected, additional target to get latest release version

- .github/workflows/main-integration.yaml
> GHA main workflow definition fixed

- .github/workflows/pull-integration.yaml
> Environment for GHA

- Makefile
- hack/kyma-components.yaml
- make install needs kustomize
> Make install needs kustomize

- .github/workflows/main-integration.yaml
- Makefile
- Fixed slack notifications on main workflow, needs duplicate
> Fixed slack notifications on main workflow

- .github/workflows/main-integration.yaml
- .github/workflows/pull-integration.yaml
- Makefile
- Fix nightly scheduled integration tests
> Fix nightly scheduled integration tests

- .github/workflows/main-integration.yaml
> fix workflow bugs

- .github/actions/upgrade-test/action.yaml
- .github/workflows/pull-integration.yaml
This reverts commit 7eb9c736f89e4f0829294a30ce7d2e21f9a8b0eb.
- ...
- ...
- ...
> Revert "Fix ref (#576)"

- .github/workflows/main-integration.yaml
- .github/workflows/pull-integration.yaml
- Temporarily turn off upgrade test (waiting for the first module test release)
> Temporarily remove upgrade test from workflows

- .github/workflows/create-release.yaml
- Release artifacts are built by `rel*` jobs
> Release workflow waiting for rel prow jobs

- docs/contributor/04-10-technical-design.md
- docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md
- docs/user/custom-resources/apigateway/04-10-kyma-gateway.md
- Edit rendering of two notes: one in [Tech design](https://github.com/kyma-project/api-gateway/blob/mod-dev/docs/contributor/04-10-technical-design.md#apirule-controller) doc and one in [APIGateway](https://github.com/kyma-project/api-gateway/blob/mod-dev/docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md#specification) CR doc
- Fix a broken link
> Edit formatting

- .github/workflows/pull-integration.yaml
When using `pull-request-target` flow, the used code for running tests is the one from base branch. Until we use a PR ref for checkout no code changes can be added for running the tests
- Use pull request ref in PR tests
> Use pull request ref in PR tests

- Makefile
- tests/integration/testsuites/gateway/scenario.go
- Enable Gateway integration tests in integration-test pipeline
> Enable Gateway integration tests

- .github/workflows/main-integration.yaml
- Makefile
- hack/kyma-components-no-istio.yaml
- hack/kyma-components.yaml
- Fix actions not running on main, because of upgrade-tests dependency.
- Remove old kyma component certificate, that is not part of API Gateway.
> Fix actions on main

- .github/workflows/pull-request.yaml
> Add missing release branch trigger for Pull Request workflow

- .github/actions/k8s-compatibility-test/action.yaml
- .github/workflows/pull-integration.yaml
- kubernetes compatibility check
> k8s compatibility check

- sec-scanners-config.yaml
> udpate sec scanner

- config/ui-extensions/apigateways/general
- Disable creation and removal of APIGateway CR
> disable deleting and creating APIGateway CR

- sec-scanners-config.yaml
> update sec scanner

- .github/workflows/pull-integration.yaml
This reverts commit 2368c7e4c8b15a3ee6554fea51c7763324c1cddb.
- ...
- ...
- ...
> Revert "change trigger to pull_request"

- internal/reconciliations/gateway/certificate.go
- tests/integration/testsuites/gateway/features/kyma_gateway_gardener.feature
- Update Gardener certificate name to "kyma-tls-cert"
> Update Gardener certificate name to "kyma-tls-cert"

- README.md
- docs/contributor/01-00-installation.md
- docs/release-notes/2.0.0.md
- docs/release-notes/template.md
- Release notes for 2.0.0 release
> Release notes for 2.0.0 release

- .github/workflows/pull-integration.yaml
- Run upgrade tests on PRs with PR codebase
> Run upgrade tests on PRs with PR codebase

- .github/actions/integration-tests/action.yaml
- .github/actions/k8s-compatibility-test/action.yaml
- .github/actions/upgrade-test/action.yaml
- .github/workflows/create-release.yaml
- .github/workflows/main-integration.yaml
- .github/workflows/pull-integration.yaml
- .github/workflows/pull-request.yaml
- tests/integration/scripts/deploy-latest-release-to-cluster.sh
- Fix checkout on PR upgrade-tests
> Fix checkout on PR upgrade-test

- .github/dependabot.yml
- Add dependabot config for release-2.0 branch
> Add dependabot config for release-2.0 branch

- Makefile
- README.md
- config/manager/manager.yaml
- docs/contributor/01-00-installation.md
- Don't deploy kyma-system with api-gateway manifest
> Don't deploy kyma-system

- config/ui-extensions/apirules/dataSources
- config/ui-extensions/apirules/details
- config/ui-extensions/apirules/form
- config/ui-extensions/apirules/general
- config/ui-extensions/apirules/kustomization.yaml
- config/ui-extensions/apirules/list
- config/ui-extensions/apirules/presets
- config/ui-extensions/apirules/translations
- config/ui-extensions/kustomization.yaml
- Copy APIRules ui + add token_from
> Copy APIRules ui + add token_from

- controllers/gateway/apirule_controller.go
- Get an ApiRule from the cluster just before updating it's status, preventing object already modified errors
#465
> Fix object already modified error

- config/ui-extensions/apirules/details
- config/ui-extensions/apirules/form
- config/ui-extensions/apirules/translations
- Trusted Issuers: Show warning on HTTP
- JWKS URLs: Show warning on HTTP
> Show warning on HTTP

- sec-scanners-config.yaml
- Add Ory to modular sec scanner
- ...
- ...
> Add ory to modular sec scanner

- .github/workflows/vulnerabilities-check.yaml
- To avoid blocking PRs and releases, we should not run vulnerability check on PRs
> Remove vulnerability check from PRs

- config/ui-extensions/apirules/form
- Make services not required: https://github.com/kyma-project/kyma-dashboard/pull/243
> Make [].services not required

- config/ui-extensions/apirules/general
> Update APIRule documentation link

- Makefile
- controllers/operator/apigateway_controller.go
- controllers/operator/apigateway_controller_test.go
- docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md
- tests/integration/testsuites/gateway/features/kyma_gateway.feature
- tests/integration/testsuites/gateway/manifests/api-gateway.yaml
- tests/integration/testsuites/gateway/scenario.go
- Limit number of reconciled APIGateway CRs to only one - the oldest
> Limit reconciled APIGateway CRs to only one

- .github/workflows/main-integration.yaml
- Remove reference to non existing job in gh actions
> Remove reference to no longer existing job in gh actions

- sec-scanners-config.yaml
- Update security scanner config
> Update security scanner config

- .github/workflows/pull-integration.yaml
- Use collaborator check only on `wait for image build`
> Use collaborator check only on `wait for image build`

- README.md
- docs/user/README.md
- Correct the link to the contributor folder
> Correct the README

- Makefile
- README.md
- controllers/operator/apigateway_controller.go
- Include istio-injection label when creating kyma-system ns
> Include istio-injection label when creating kyma-system ns

- .github/actions/integration-tests/action.yaml
- .github/actions/k8s-compatibility-test/action.yaml
- .github/actions/upgrade-test/action.yaml
- .github/workflows/main-integration.yaml
- .github/workflows/pull-integration.yaml
- Makefile
- hack/kyma-components.yaml
- tests/integration/scripts/custom-domain-gardener.sh
- tests/integration/scripts/test-gardener.sh
(cherry picked from commit 936332745a7f23598df3bd11f7e8a309a45b4cad)
- Fix failing integration tests by cherry picking Cleanup jobs after modularisation (#745)
> Fix release branch integration tests

- tests/integration/scripts/deploy-latest-release-to-cluster.sh
- Fix upgrade test script for release branches
> Fix upgrade test script for release branches

- .github/workflows/main-integration.yaml
- Fix image repository path in workflow
> Fix image repository path in workflow

- sec-scanners-config.yaml
- Security scanner config update
> Security scanner config update

- config/ui-extensions/apirules/form
- docs/release-notes/2.1.1.md
- Add missing HTTP methods to rule methods
- Add missing HTTP methods to CORS allow methods
> Add missing HTTP methods in APIRule UI

- config/ui-extensions/apirules/form
- docs/release-notes/2.1.1.md
- Add missing HTTP methods to rule methods
- Add missing HTTP methods to CORS allow methods
- https://github.com/kyma-project/api-gateway/pull/815
> Cherry Pick: Add missing HTTP methods in APIRule UI (#815)

- .github/dependabot.yml
- Update release branch in Dependabot config to point to latest release
> Update release branch in Dependabot config

- sec-scanners-config.yaml
- Update api-gateway-manager image for security scanners
> Update api-gateway-manager image for security scanners

- tests/integration/testsuites/gateway/scenario.go
- Fix custom-domain integration tests
> Fix custom-domain integration tests

- docs/contributor/01-00-installation.md
- Fix a link to a non-existing doc
- 
> Update a link

- .github/workflows/main-integration.yaml
> Fix script ref in job

- .github/workflows/create-release.yaml
- Check if release tag is applied to sec-scanner config
**Runs**
- ![#c5f015](https://placehold.co/15x15/00ff14/00ff14.png) [Green](https://github.com/barchw/api-gateway-1/actions/runs/7697419445/job/20974405667)
- ![#f03c15](https://placehold.co/15x15/f03c15/f03c15.png) [Red](https://github.com/barchw/api-gateway-1/actions/runs/7695625750/job/20968912294)
> Automated check for security scanner config

- config/rbac/role.yaml
- controllers/operator/apigateway_controller.go
- controllers/operator/suite_test.go
- docs/release-notes/2.2.0.md
- internal/reconciliations/oathkeeper/oathkeeper.go
- internal/reconciliations/oathkeeper/oathkeeper_test.go
- internal/reconciliations/oathkeeper/pod_disruption_budget.go
- internal/reconciliations/oathkeeper/pod_disruption_budget.yaml
- tests/integration/pkg/resource/manager.go
- tests/integration/testsuites/gateway/features/kyma_gateway.feature
- Add PodDisruptionBudget for Oathkeeper to have better resiliency, especially during node upgrades.
> Add PodDisruptionBudget for Oathkeeper

- docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
- docs/user/custom-resources/apirule/04-20-apirule-istio-jwt-access-strategy.md
- docs/user/custom-resources/apirule/04-30-apirule-jwt-ory-and-istio-comparison.md
- docs/user/custom-resources/apirule/04-50-apirule-authorizations.md
- docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-02-404-not-found.md
- docs/user/troubleshooting-guides/03-10-dns-mgt/03-10-dns-mgt-connection-refused.md
- docs/user/tutorials/01-10-setup-custom-domain-for-workload.md
- docs/user/tutorials/01-40-expose-workload/01-40-expose-workload-apigateway.md
- docs/user/tutorials/01-40-expose-workload/01-41-expose-multiple-workloads.md
- docs/user/tutorials/01-40-expose-workload/01-42-expose-workloads-multiple-namespaces.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/01-50-expose-and-secure-workload-oauth2.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/01-52-expose-and-secure-workload-jwt.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/01-54-expose-and-secure-workload-with-certificate.md
- docs/user/tutorials/01-60-security/01-61-mtls-selfsign-client-certicate.md
- docs/user/tutorials/01-60-security/01-62-set-up-idp.md
- Update the syntax used for the notes
#18552
> Update the notes' style

- sec-scanners-config.yaml
- Update api-gateway-manager version for security scanners
> Update api-gateway-manager version for security scanners

- docs/contributor/04-10-technical-design.md
- docs/release-notes/2.2.0.md
- docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md
- Update the docs
- Add release notes
#879
> Update the docs related to Warning state on duplicate APIGateway CRs

- sec-scanners-config.yaml
- Update manager image in sec-scanners-config
> Update manager image in sec-scanners-config

- sec-scanners-config.yaml
> chore: bump sec-scanners-config.yaml image to 2.2.0

- docs/contributor/01-30-api-rule-dependencies.md
- docs/contributor/04-10-technical-design.md
- docs/release-notes/2.0.0.md
- docs/release-notes/2.2.0.md
- docs/user/custom-resources/apigateway/04-10-kyma-gateway.md
- docs/user/troubleshooting-guides/03-50-certificates-gardener.md
- docs/user/tutorials/01-30-set-up-mtls-gateway.md
- Use 'in a cluster' instead of 'on a cluster'
https://github.com/kyma-project/kyma/issues/18581
> Use 'in a cluster' instead of 'on a cluster'

- docs/user/tutorials/01-00-create-workload.md
- docs/user/tutorials/01-30-set-up-mtls-gateway.md
- docs/user/tutorials/01-40-expose-workload/01-40-expose-workload-apigateway.md
- Use custom or Kyma domain placeholder in the mTLS tutorial
- Disable link checker for a CloudFlare link (it reports errors while the link works fine)
> Use custom or Kyma domain placeholder in the mTLS tutorial

- internal/reconciliations/gateway/dns_entry_test.go
- internal/reconciliations/resource.go
- sec-scanners-config.yaml
- Cherry Pick https://github.com/kyma-project/api-gateway/pull/864
- Update sec-scanners-config to next release version
> Add garden Annotation to DNSEntry 

- docs/release-notes/2.2.1.md
> Add 2.2.1 release notes

- .github/dependabot.yml
- Update dependabot.yml for release-2.2 branch
> Update dependabot.yml for release-2.2 branch

- tests/integration/scripts/custom-domain-gardener-aws-gh.sh
- tests/integration/scripts/custom-domain-gardener-gcp-gh.sh
- tests/integration/scripts/provision-gardener-gh.sh
> Define gardenlinux image

- docs/user/tutorials/01-30-set-up-mtls-gateway.md
- Disable a Cloud Flare link - it is displayed by the Lick Check as broken although it works fine
> Disable Link Check for a Cloud Flare link

- internal/reconciliations/oathkeeper/maester/cluster_role_binding.go
- internal/reconciliations/oathkeeper/maester/service_account.go
- Wait for resources before deploying oathkeeper
> Wait for cluster role and service account before deploying oathkeeper

- config/ui-extensions/apigateways/details
- Remove tabs from APIGateway CR UI to be consistent with other module CRs
> Remove tabs from APIGateway CR UI

- main.go
> Trigger release pipelines

- config/manager/manager.yaml
- sec-scanners-config.yaml
- Cherry-pick https://github.com/kyma-project/api-gateway/pull/957
- Update security scanners config
> Update managers metrics address

- docs/release-notes/2.3.1.md
> Add 2.3.1 release notes

- docs/release-notes/2.2.2.md
- docs/release-notes/2.3.1.md
- Add release notes that only exist on release branch
> Add release notes for 2.2.2 and 2.3.1

- .github/actions/integration-test-gardener/action.yaml
- .github/actions/integration-tests/action.yaml
- .github/actions/k8s-compatibility-test/action.yaml
- .github/actions/upgrade-test/action.yaml
- Bump golang in cicd test jobs
> Bump golang in cicd test jobs

- .github/workflows/pull-gitleaks.yaml
- .gitleaks.toml
/kind chore
/area ci
Add gitleaks to repo
> chore: add gitleaks to repo

- docs/contributor/adr/0004-api-gateway-cr-status-improvements.md
> Fix link in the adr folder

- config/manager/manager.yaml
- Priority class name for api-gateway
> Priority class name for api-gateway

- .github/workflows/pull-integration-release.yaml
- .github/workflows/pull-integration.yaml
- tests/integration/main_test.go
- Adjust workflow to run proper action
> Adjust workflow to run proper action

- docs/contributor/01-00-installation.md
- tests/ui/tests/scripts/k3d-local-dev.sh
- Deprecate kyma provision k3d command
- https://github.com/kyma-project/kyma/issues/18652
> Deprecate kyma provision k3d command

- .github/dependabot.yml
- Dependabot for release branch release-2.4
> Dependabot for release 2.4

- config/ui-extensions/apigateways/general
- Unify APIGateway CR's description and the link to the API Gateway documentation to be consistent with all CR descriptions in Kyma dashboard
https://github.com/kyma-project/kyma/issues/18321
> Unify CR description in Kyma dashboard

- internal/reconciliations/gateway/certificate_test.go
- change from one week to one month
> Fail certificate expire test one month before actual cert expiration

- apis/gateway/v1beta2/apirule_types.go
- config/crd/bases/gateway.kyma-project.io_apirules.yaml
- controllers/gateway/api_controller_integration_test.go
- Add validation to allow only one host to be configured in v1beta2
> Allow only one hosts for APIRule v1beta2

- tests/ui/tests/cypress.config.ts
- tests/ui/tests/package.json
- tests/ui/tests/scripts/k3d-ci-kyma-dashboard-integration.sh
- tests/ui/tests/support/input.ts
- Fix issue with APIRule Name not scrolling into view
- don't use latest version of Kyma dashboard, because Chromium was constantly crashing
> Fix an issue in the UI tests 

- docs/user/troubleshooting-guides/03-40-api-rule-troubleshooting.md
- Use commands `kubectl get apirules.v1beta1...` instead of `kubectl get apirule ...` 
> Adjust the "get apirule" kubectl command

- .github/actions/integration-test-gardener/action.yaml
- .github/workflows/main-integration.yaml
- .github/workflows/pull-integration-release.yaml
- hack/ci/gardener_kubeconfig.sh
- Don't use separate variable for gardener live tests
> Revert separate variable for Gardener live

- docs/user/_sidebar.md
- Fix the link to the Issues with APIRules and Service Connection doc
> Fix a broken link

- .github/workflows/pull-integration.yaml
- tests/integration/pkg/hooks/verify-controller-restart.go
- tests/integration/testsuites/custom-domain/scenario.go
- tests/integration/testsuites/gateway/scenario.go
- tests/integration/testsuites/upgrade/scenario.go
> Add restart hook to verify behaviour wrt Istio test flakiness

- .github/workflows/pull-integration.yaml
- .github/workflows/pull-request.yaml
- .github/workflows/pull-unit-lint.yaml
- .github/workflows/ui-tests.yaml
- .github/workflows/verify-commit-pins.yaml
/kind chore
/area ci
Use the same approach as for istio repository
> refactor: unify workflows into single pipeline

- .github/workflows/pull-request.yaml
/kind chore
/area ci
Use the same approach as for istio repository
> refactor: add lint and unit tests

- docs/user/tutorials/01-00-create-workload.md
/kind bug
/area documentation
Fix typo in 01-00-create-workload.md. This fixes definition of Service for exposing rule.
> docs: fix typo in 01-00-create-workload.md

- apis/gateway/v2alpha1/jwt_conversion.go
- controllers/gateway/apirule_controller.go
- docs/contributor/draft/apirule-migration.md
- internal/processing/istio/reconciliation.go
- internal/processing/migration/access_rule_processor.go
- internal/processing/migration/as_validator.go
- internal/processing/migration/jwt_validator.go
- internal/processing/migration/reconciliation.go
- internal/processing/ory/reconciliation.go
- internal/processing/reconciliation.go
- internal/processing/types.go
- internal/validation/validate.go
> PoC for APIRule migration

- .github/pull-request-template.md
- Add Pre-Merge Checklist to the PR template
> Add Pre-Merge Checklist to the PR template

- .github/workflows/rollout-module.yaml
- Add module rollout workflow
- Keep naming of existing default CR in API Gateway releases. We might want to change this in the future.
> Module Rollout Workflow

- docs/user/tutorials/01-20-set-up-tls-gateway.md
- remove characters after EOF in the TLS tutorial
> Remove blank spaces

- .github/actions/integration-test-gardener/action.yaml
- .github/actions/integration-tests/action.yaml
- tests/integration/pkg/helpers/api_rule.go
/kind feature
/area ci
Add some additional log spitting and collection to gather more insights on potential failures only if something is wrong with the jobs.
> feat: more log gathering in int test jobs

- docs/user/tutorials/01-20-set-up-tls-gateway.md
- Remove blank characters in the TLS tutorial
> Remove empty spaces

- controllers/gateway/api_controller_integration_test.go
- controllers/gateway/apirule_controller_status_integration_test.go
- controllers/gateway/apirule_controller_validation_integration_test.go
- controllers/gateway/apirule_timeout_integration_test.go
- controllers/gateway/suite_test.go
- controllers/operator/apigateway_controller_integration_test.go
- controllers/operator/apigateway_controller_test.go
- controllers/operator/suite_test.go
- controllers/status_test.go
- internal/clusterconfig/clusterconfig_test.go
- internal/helpers/service_test.go
- internal/processing/cleaner_test.go
- internal/processing/processors/istio/authorization_policy_processor_test.go
- internal/processing/processors/ory/reconciliation_test.go
- internal/resources/resources_test.go
- internal/validation/v1beta1/v1beta1_test.go
- tests/integration/pkg/hooks/api-gateway.go
- tests/integration/pkg/resource/manager.go
- tests/integration/testsuites/custom-domain/testsuite.go
- Replace all context TODO with Background
> Replace all context TODO

- .github/actions/integration-test-gardener/action.yaml
- .github/actions/integration-tests/action.yaml
- tests/integration/pkg/testcontext/config.go
/kind bug
/area ci
* increase retry count in all scenarios to 60 - 24 seems not enough.
* fix getting apirules
* add getting apigateways
> bug: increase retry attempts for all scenarios

- .github/actions/integration-tests/action.yaml
/kind chore
/area ci
* add getting logs and deployments for ory oathkeeper
> chore: add oathkeeper log collection

- apis/gateway/v1beta1/apirule_types.go
- config/crd/bases/gateway.kyma-project.io_apirules.yaml
- Remove deprecation warning for APIRule v1beta1
> Remove deprecation warning for APIRule v1beta1

- config/conversion_webhook/service.yaml
> bug: add name to port in service.yaml

- .github/workflows/main-integration.yaml
- .github/workflows/pull-integration-release.yaml
- fix input for upgrade main int test
> Fix main int upgrade int test input

- config/conversion_webhook/service.yaml
- docs/release-notes/2.4.1.md
> Fix webhook bug

- sec-scanners-config.yaml
> chore: sec-scanners-config.yaml

- main.go
- Exclude Secret resources from manage client cache
https://github.tools.sap/kyma/backlog/issues/5943
> Exclude Secret resources from manage client cache

- tests/integration/scripts/provision-gardener-gh.sh
/kind bug
/area ci
Assign empty variables before entering loop to fix unbound variable error
> bug: fix unbound variable in checking for apiserver

- docs/user/README.md
- ...
https://github.com/kyma-project/kyma/issues/18735
> Change enable and disable to add and delete in the api-gateway repo

- main.go
- Reconcile every 30 minutes instead of 1 hour
As decided in #1175
> Change reconciliation time to 30 minutes

- tests/integration/scripts/provision-gardener-gh.sh
/kind bug
/area ci
Gardener sometimes fails when applying shoot cluster. More than that, it's rather a flake because rerunning the job usually resolves the problem. This option ensures that we at least tried to create the cluster 2 more times, to work around gardener seed cluster fluctuations.
> bug: add retry logic for creating shoot clusters

- .github/dependabot.yml
- Bump dependabot config for 2.5
> Bump dependabot config for 2.5

- hack/ci/custom-domain-gardener.sh
> cicd: fix wrong script reference

- docs/contributor/adr/0009-request-modifiers.md
- Add ADR for request modifiers
> ADR for request modifiers

- sec-scanners-config.yaml
- Update security scanner configuration
> Update security scanner configuration

- apis/gateway/v2alpha1/apirule_types.go
- config/crd/bases/gateway.kyma-project.io_apirules.yaml
- controllers/gateway/api_controller_integration_test.go
> Gateway validation error message

- .github/actions/upgrade-test/action.yaml
> Remove leftover cicd

- .github/actions/integration-test-gardener/action.yaml
- Fix upload logs/artefacts on test-gardener action when using matrix in workflow
> Fix upload logs/artefacts on test-gardener action when using matrix

- hack/ci/custom-domain-gardener.sh
- hack/ci/gardener_kubeconfig.sh
- hack/ci/provision-gardener.sh
- Fix gardener provision bash scripts
> Fix gardener provision bash scripts

- sec-scanners-config.yaml
- Update to latest manager image version
> Update security scanners config

- .github/workflows/main-integration.yaml
- Dockerfile
> bug: fix wrong sha reference

- hack/ci/provision-gardener.sh
- tests/integration/pkg/resource/manager.go
- Add more logs to resource operations
- Increase timeout
> Add more logs to resource operations

- .github/workflows/main-integration.yaml
/kind bug
Rename api-gateway to api-gateway-manager
#1271
> bug: fix typo in main-integration.yaml

- .github/dependabot.yml
- Bump dependabot config for 2.6.0 release
> Bump dependabot config for 2.6.0 release

- sec-scanners-config.yaml
- Update manager tag in sec-scanners-config
> Update manager tag in sec-scanners-config

- docs/user/custom-resources/README.md
- docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
- docs/user/custom-resources/apirule/README.md
- docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/README.md
- docs/user/tutorials/01-40-expose-workload/README.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/README.md
- Adjust migration notes. More details with be added when we publish the migration procedure
> Adjust migration notes

- internal/validation/v2alpha1/hosts.go
- internal/validation/v2alpha1/hosts_test.go
- Ensure shot host also includes ref gateway domain when checking for occupied VirstualService host
https://github.com/kyma-project/api-gateway/issues/1247
> Ensure shot host with ref gateway domain used for occupied vs check

- .github/workflows/main-integration.yaml
- Move build to separate job, since it's a reusable workflow
- https://github.com/kyma-project/api-gateway/issues/1271
> Move build to separate job in main int test

- .github/workflows/pull-build-push.yaml
- .github/workflows/pull-integration-release.yaml
- .github/workflows/pull-request-release.yaml
- new pipeline for release pull requests with image-builder introduced
#1271
> release pull request pipeline

- .github/workflows/main-integration.yaml
- Make build job optional in main integration tests
- https://github.com/kyma-project/api-gateway/issues/1271
> Run integration tests in schedule without build

- .github/workflows/create-release.yaml
- Add image-builder to create release workflow
- https://github.com/kyma-project/api-gateway/issues/1271
> Add image-builder to create release workflow

- .github/workflows/create-release.yaml
- .github/workflows/pull-build-push.yaml
- .github/workflows/pull-integration-release.yaml
- .github/workflows/pull-request-release.yaml
- cherry-pick #1321 #1324
- #1271
> Cherry-pick release branch related workflows

- .github/dependabot.yml
- Switched dependabot config from 2.6 to 2.7 release branch
> Update dependabot.yml (release-2.7 branch)

- .github/dependabot.yml
- Ignore GitHub Actions patches
> Ignore GitHub Actions patches

- docs/release-notes/2.8.0.md
/kind chore
/area documentation
/cc @nataliasitko
> docs: release notes for Remove hard dependency to Gardener DNSEntry and Certificate resources

- docs/user/tutorials/01-00-create-workload.md
- docs/user/tutorials/01-10-setup-custom-domain-for-workload.md
- docs/user/tutorials/01-20-set-up-tls-gateway.md
- docs/user/tutorials/01-30-set-up-mtls-gateway.md
- docs/user/tutorials/01-40-expose-workload/v2alpha1/01-40-expose-workload-apigateway.md
- docs/user/tutorials/01-40-expose-workload/v2alpha1/01-43-expose-workload-short-host-name.md
- docs/user/tutorials/01-40-expose-workload/v2alpha1/01-43-expose-workload-short-host.md
- Tutorial for short host name
https://github.com/kyma-project/api-gateway/issues/1335
> Tutorial for short host name

- apis/gateway/v2alpha1/apirule_types.go
- config/crd/bases/gateway.kyma-project.io_apirules.yaml
- controllers/gateway/api_controller_integration_test.go
- controllers/gateway/apirule_controller.go
- internal/helpers/hosts.go
- internal/helpers/hosts_test.go
- Fix FQDN validation, allowing 1 char labels and 2 chars top level domain
https://github.com/kyma-project/api-gateway/issues/1373
> Fix FQDN validation, allowing 1 char labels and 2 chars top level domain

- controllers/gateway/apirule_controller.go
- controllers/gateway/discover_gateway_test.go
- tests/integration/pkg/helpers/api_rule.go
- Check for Gateway existence after requesting v2alpha1 APIRule
> fix: Check for Gateway existence after requesting v2alpha1 APIRule

- docs/user/tutorials/01-60-security/01-62-set-up-idp.md
> Fix link in security

- .github/workflows/main-integration.yaml
- .github/workflows/pull-build-push.yaml
- .github/workflows/pull-request-release.yaml
- .github/workflows/pull-request.yaml
- .github/workflows/sync-external-images.yaml
- docs/contributor/04-30-ci-cd.md
- external-images.yaml
- Add workflow for image syncer
- Ignore new file with images to sync in existing workflows
- CI/CD documentation
> Add new workflow for image syncer

- docs/contributor/04-30-ci-cd.md
- external-images.yaml
> Add link for sync-external-images to CI/CD docs

- config/ui-extensions/apirules-v2alpha1/dataSources
- config/ui-extensions/apirules-v2alpha1/details
- config/ui-extensions/apirules-v2alpha1/form
- config/ui-extensions/apirules-v2alpha1/general
- config/ui-extensions/apirules-v2alpha1/kustomization.yaml
- config/ui-extensions/apirules-v2alpha1/list
- config/ui-extensions/apirules-v2alpha1/presets
- config/ui-extensions/apirules-v2alpha1/translations
- config/ui-extensions/apirules/general
- config/ui-extensions/kustomization.yaml
- docs/release-notes/2.8.0.md
- tests/ui/tests/fixtures/apiRuleV2alpha1.yaml
- tests/ui/tests/package.json
- tests/ui/tests/support/k8sclient/apiRule.ts
- tests/ui/tests/support/k8sclient/commands.ts
- tests/ui/tests/support/navigation.ts
- tests/ui/tests/tests/api-rule-v2alpha1.spec.ts
- Add UI for APIRule v2alpha1
- Exclude v2alpha1 APIRules from v1beta1 UI list and vice versa
- Add Cypress tests
- Log CPU and memory usage during UI test execution to get more details about Chromium crash
- https://github.com/kyma-project/api-gateway/issues/1353
> APIRule v2alpha1 UI

- config/ui-extensions/apirules-v2alpha1/form
- Add required flag for access strategy in v2alpha1 form
- https://github.com/kyma-project/api-gateway/issues/1353
> Add required flag for access strategy in APIRule v2alpha1 form

- .github/workflows/main-integration.yaml
- .github/workflows/pull-integration-release.yaml
- Add zero downtime migration test to Slack notification
> Add zero downtime migration test to Slack notification

- docs/release-notes/2.8.0.md
> RN for fix in APIRule v2alpha1 hosts validation

- .github/dependabot.yml
- Update dependabot.yml for release-2.8
> Update dependabot.yml for release-2.8

- tests/integration/pkg/hooks/ext-auth.go
- Change function used to create ext-auth in tests hook
> Reduce int tests flakiness

- docs/user/tutorials/01-40-expose-workload/01-42-expose-workloads-multiple-namespaces.md
- docs/user/tutorials/01-40-expose-workload/v2alpha1/01-42-expose-workloads-multiple-namespaces.md
- Fix links to Istio documentation
https://github.com/kyma-project/istio/pull/999
> Fix links to Istio documentation

- .github/workflows/pull-integration.yaml
- .github/workflows/pull-unit-lint.yaml
- .github/workflows/ui-tests.yaml
- .github/workflows/verify-commit-pins.yaml
GitHub Actions 🤡 
/kind bug
/area ci
> bug: change any_changed to any_modified and add back output

- .github/ISSUE_TEMPLATE/issue.md
- Missing github required template metadata
> Fix issue template

- .github/actions/integration-tests/action.yaml
- .github/actions/k8s-compatibility-test/action.yaml
- .github/workflows/main-integration.yaml
- .github/workflows/pull-integration-release.yaml
- .github/workflows/pull-integration.yaml
/kind bug
/area ci
I can't access secret in actions. Move assignment into workflow job.
- ...
> bug: fix incorrect secret usage

- .github/actions/integration-tests/action.yaml
- .github/actions/k8s-compatibility-test/action.yaml
- .github/workflows/main-integration.yaml
- .github/workflows/pull-integration-release.yaml
- .github/workflows/pull-integration.yaml
- .github/workflows/pull-request-release.yaml
- .github/workflows/pull-request.yaml
- .github/workflows/ui-tests.yaml
/kind bug
/area ci
I can't access secret in actions. Move assignment into workflow job.
> bug: fix incorrect secret usage (#1435)

- sec-scanners-config.yaml
- Bump api-gateway-manager main image for sec-scanners-config.yaml
> Bump api-gateway-manager main image for sec-scanners-config.yaml

- sec-scanners-config.yaml
> chore: update sec-scanners-config.yaml

- hack/ci/provision-gardener.sh
- Increase timeout to 25m to avoid flakiness due to cluster creation timeouts
> Increase timeout for provisioning Gardener cluster

- tests/ui/tests/cypress.config.ts
- tests/ui/tests/support/navigation.ts
- Increase retries and waits to see if it helps to reduce flakiness
> Reduce UI test flakiness

- docs/release-notes/2.10.0.md
- docs/release-notes/2.11.0.md
- Move 2.11.0 release notes to 2.10.0
> Move 2.11.0 release notes to 2.10.0

- .github/dependabot.yml
- Update dependabot for rel 2.10
> Update dependabot for rel 2.10

- .github/workflows/pr-add-dependabot-to-project.yaml
/kind feature
/area ci
Run workflow on pull request to automate adding dependabot PRs to board.
> feat: workflow to add dependabot PRs to project

- docs/contributor/adr/0011-rate-limit.md
- Move rate limit ADR from Istio Module repository
- Adjust to the APIGateway module context
> Move rate limit ADR from Istio Module repository

- docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-01-401-unauthorized-403-forbidden.md
- docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-02-404-not-found.md
- docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-03-500-server-error.md
- docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-40-api-rule-troubleshooting.md
- docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/v2alpha1/03-01-401-unauthorized-403-forbidden.md
- docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/v2alpha1/03-40-api-rule-troubleshooting.md
- docs/user/troubleshooting-guides/03-10-dns-mgt/03-10-dns-mgt-connection-refused.md
- docs/user/troubleshooting-guides/03-10-dns-mgt/03-11-dns-mgt-could-not-resolve-host.md
- docs/user/troubleshooting-guides/03-10-dns-mgt/03-12-dns-mgt-resource-ignored.md
- docs/user/troubleshooting-guides/03-20-cert-mgt-issuer-not-created.md
- docs/user/troubleshooting-guides/03-30-gateway-not-reachable.md
- docs/user/troubleshooting-guides/03-50-certificates-gardener.md
- docs/user/troubleshooting-guides/03-60-apirule-conversion-webhook-cert-issue.md
- docs/user/troubleshooting-guides/03-70-empty-apirule-spec.md
- Replace 'remedy' with 'solution' in the API Gateway troubleshooting guides
> Replace 'remedy' with 'solution' in the troubleshooting guides

- hack/ci/custom-domain-gardener.sh
- hack/ci/provision-gardener.sh
- tests/integration/env_vars_custom_domain.sh
- Custom domain tests with KUBECONFIG env variable 
> Custom domain tests with KUBECONFIG env variable 

- tests/integration/pkg/auth/oauth2-server.go
- tests/integration/testsuites/custom-domain/scenario.go
- proper base64 encoder (with padding) used when creating secret
- removed obsolete OIDC URL from logs
> Fixed failing tests: base64 encoding with padding

- hack/ci/custom-domain-gardener.sh
- Adding KYMA_DOMAIN variable into custom-domain.gardener.sh, so it is visible to other make targets
> Adding KYMA_DOMAIN variable into custom-domain.gardener.sh, so it is visible to other make targets

- internal/processing/reconciliation.go
> Log errorMap before updateStatus fails

- tests/integration/main_test.go
- Only use scenario initializer for v2alpha1 tests
> Only use scenario initializer for v2alpha1 tests

- internal/reconciliations/oathkeeper/pod_disruption_budget.yaml
/kind bug
Change PodDisruptionBudget from `  minAvailable: 1` to `maxUnavailable: 1` - recommendation from SRE.
> bug: change ORY PodDisruptionBudget

- docs/user/tutorials/01-10-setup-custom-domain-for-workload.md
- internal/reconciliations/gateway/certificate.yaml
- tests/integration/testsuites/custom-domain/manifests/resources.yaml
- Add `issuerRef` to `kyma-tls-cert` certificate
> Add issuerRef to kyma-tls-cert certificate

- .github/actions/slack-notification-failed-workflow/action.yaml
- Fix trailing comma in slack notification action
> Fix trailing comma in slack notification action

- docs/contributor/02-10-testing-strategy.md
- docs/contributor/adr/0012-testing-strategy.md
- Testing strategy for APIGateway module
> Testing strategy for APIGateway module

- .github/actions/slack-notification-failed-workflow/action.yaml
- .github/workflows/post-main-integration.yaml
- Fix slack notification action and adjust post workflow name
> Fix slack notification action and adjust post workflow name

- .github/actions/slack-notification-failed-workflow/action.yaml
- .github/workflows/post-main-integration.yaml
- Bump slack action for failed workflow notification
> Bump slack action for failed workflow notification

- Dockerfile
- controllers/gateway/apirule_controller.go
- controllers/gateway/reconcile_result.go
- Fix requeue on error of APIRule
- Strip symbols - small improvement on build speed
> Fix requeue on error of APIRule

- README.md
- docs/release-notes/2.2.0.md
- docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md
- docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
- docs/user/technical-reference/05-00-api-gateway-operator-parameters.md
- Fix broken links
- add status tables to the CRs' documentation. Accidentaly removed with https://github.com/kyma-project/api-gateway/pull/1541/files?short_path=2ee7a0b#diff-2ee7a0bcb3221b7ab9245139d684ef436bb522d5aab6877dfb1005f5524316dd
> Fix broken links and move CRs' status descriptions

- .github/actions/get-latest-sha/action.yaml
- Fixed workflow name used to query for the Docker image to be used in e2e tests
> Fixed workflow name to get the correct image for tests

- controllers/gateway/apirule_controller.go
- Use error requeue on convert and update
> Use error requeue on convert and update

- apis/gateway/ratelimit/v1alpha1/ratelimit_types.go
- config/crd/bases/gateway.kyma-project.io_ratelimits.yaml
- config/rbac/role.yaml
- controllers/gateway/ratelimit/ratelimit_controller.go
- controllers/gateway/ratelimit/ratelimit_controller_integration_test.go
- controllers/gateway/ratelimit/ratelimit_enabled.go
- internal/dependencies/dependencies.go
/kind bug
* Requeue reconciliation every 3 minutes, accepting downtime
* Add warning state to the CR status
* Adjust tests
Restore watching should be handled in a follow-up anytime soon.
#1516
> bug: RateLimit: replace Watch with polling

- .github/workflows/call-pull-integration.yaml
- .github/workflows/pull-request.yaml
- Adjust pull request cicd workflow to the new strategy according to #1523 
Related issues:
https://github.com/kyma-project/api-gateway/issues/1546
> Adjust pull request cicd workflow to the new strategy

- docs/user/os-quick-start.md
- docs/user/tutorials/01-40-expose-workload/01-40-expose-workload-apigateway.md
- docs/user/tutorials/01-40-expose-workload/01-41-expose-multiple-workloads.md
- docs/user/tutorials/01-40-expose-workload/01-42-expose-workloads-multiple-namespaces.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/01-50-expose-and-secure-workload-oauth2.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/01-52-expose-and-secure-workload-jwt.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/01-53-expose-and-secure-workload-istio.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/01-54-expose-and-secure-workload-with-certificate.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/01-55-ip-based-access-with-xff.md
- Add information on the local domain to the quick start guide.
> Add information on local domain to the quick start guide

- sec-scanners-config.yaml
bump sec-scanners-config.yaml to 2.10.2
> chore: bump sec-scanners-config.yaml to 2.10.2

- .github/actions/get-latest-sha/action.yaml
- removed 'success' filter when looking for last run of post-main-integration.yaml workflows, previously scheduled builds were taking potentially very old image that is not consistent with current version of tests
> Changed get-latest-sha to get more recent image

- docs/user/tutorials/01-50-expose-and-secure-a-workload/v2alpha1/01-52-expose-and-secure-workload-jwt.md
- Fix v2alpha1 tutorial with proper path regex.
> Fix ApiRule path in docs in tutorial.

- tests/integration/pkg/hooks/api-gateway.go
- tests/integration/testsuites/gateway/scenario.go
- added an additional hook in gateway tests that waits for the apigateway dependencies (DNS entry, certificate, gateway) to be really removed
> tests: added a hook that waits for the apigateway dependencies to be removed

- .github/actions/k8s-compatibility-test-aws/action.yaml
- .github/actions/slack-notification-failed-workflow/action.yaml
- .github/workflows/schedule-main-integration.yaml
- Adjust schedule workflow according to the testing strategy
> chore: Adjust schedule workflow according to the testing strategy

- docs/user/tutorials/01-50-expose-and-secure-a-workload/v2alpha1/01-52-expose-and-secure-workload-jwt.md
- Fix code block formatting in the JWT tutorial
> Fix code block formatting in the JWT tutorial

- .github/actions/e2e-test-gardener/action.yaml
- .github/actions/k8s-compatibility-test-aws/action.yaml
- hack/ci/provision-gardener.sh
- hack/ci/shoot_aws.yaml
- hack/ci/shoot_gcp.yaml
- store shoot.yaml together with other logs
- print lastOperation in case of Gardener cluster provisioning issue
- annotate Gardener cluster with the pipeline link
> tests: annotate Gardener clusters with pipeline link, store shoot yaml

- .github/workflows/call-provision-btp-cluster.yaml
- Add additional optional inputs to BTP Provision workflow
> BTP provision QOL additions

- .github/workflows/schedule-main-integration.yaml
- Adjust name for schedule job
> Adjust name for schedule job

- hack/ci/provision-gardener.sh
- Increased timeout for the Gardener provisioning to 30 minutes
- Simplified Gardener provisioning script, so it waits only for the status.lastOperation of the shoot CR
> Increase timeout for the Gardener provisioning

- config/crd/bases/gateway.kyma-project.io_apirules.yaml
- Generate manifest for APIRule
> fix: Generate manifest for APIRule

- internal/ratelimit/validate.go
- internal/ratelimit/validate_test.go
* add new validation step to verify if descriptor bucket fillInterval is a multiple of default bucket fillInterval
* adjust error messages to use camelCase
* add unit test
That means correct behavior is token bucket fillInterval must be higher or equal than defaultBucket fillInterval and be a multiple.
#1634
> bug: fix ratelimit multiple error

- internal/reconciliations/oathkeeper/jwks_secret.go
- Use proper [algorithm name](https://www.ory.sh/docs/oathkeeper/pipeline/authn#jwt-configuration)
#1588
> Fix wrong jwks algorithm

- .github/workflows/post-main-integration.yaml
- Remove redundant get-sha job in the post workflow
> Remove redundant get-sha job in the post workflow

- docs/user/tutorials/01-70-local-rate-limit.md
- docs/user/tutorials/README.md
* Add ratelimit notice about potential DoS attack
#1607
> docs: add ratelimit notice

- docs/release-notes/2.10.3.md
> add-release-notes

- .github/workflows/create-release.yaml
> bug: fix yq fetch on noble runners

- .github/workflows/release-create-release.yaml
- Makefile
/kind bug
Remove yq usage from release-create-release.yaml workflow
Remove yq from Makefile
> bug: remove yq from release-create-release.yaml

- .github/workflows/call-integration-release.yaml
> Update failing workflow

- .github/workflows/call-integration-release.yaml
- Fix branch for upgrade tests
> Fix branch for upgrade tests

- .github/workflows/call-provision-btp-cluster.yaml
- Switch region for CCEE subaccount
> Switch region for CCEE

- apis/operator/v1alpha1/apigateway_types.go
- controllers/gateway/ratelimit/ratelimit_controller.go
- controllers/gateway/ratelimit/ratelimit_controller_integration_test.go
- controllers/operator/apigateway_controller.go
- Add checks of APIgatewayCR befor RateLimitCR
> Add checks of APIgatewayCR before RateLimitCR

- sec-scanners-config.yaml
- Upgrading sec scanner config to 2.11.2
> Upgrading sec scanner config to 2.11.2

- sec-scanners-config.yaml
> Upgrading sec scanner config to 2.10.5

- docs/user/tutorials/README.md
> Fix a broken link in the tutorials README

- .github/workflows/call-pull-integration.yaml
- Fix missing checkout ref in changes filter in call-pull-int workflow
> Fix missing checkout ref in changes filter in call-pull-int workflow

- .github/workflows/call-integration-release.yaml
- .github/workflows/post-main-integration.yaml
- Add missing deep clone for upgrade test, fix indentation for one jobs
> Add missing deep clone for upgrade test, fix indentation for one jobs

- docs/user/_sidebar.md
- fix the APIRule Migration Procedure link in the sidebar
> Fix the link to APIRule Migration Procedure in the sidebar

- .github/workflows/call-integration-release.yaml
- Remove redundant ref in upgrade test job that runs during the release
> Remove redundant ref in upgrade test in call-int-rel

- sec-scanners-config.yaml
- Adjust security scanner configuration.
> Release 3.0.0 security config

- docs/release-notes/3.0.0.md
> add RNs for APIRule 3.0.0

- docs/release-notes/3.0.0.md
* add rns 3.0
* Update 3.0.0.md
* Apply suggestions from code review
---------
- ...
> add RNs for APIRule 3.0.0 (#1739)

- sec-scanners-config.yaml
- Update sec-scanners-config.yaml
> Update sec-scanners-config.yaml for release 3.0.0

- .github/workflows/release-create-release.yaml
- Add missing write permission for release pipeline
> Add missing permission for release pipeline

- .github/workflows/release-create-release.yaml
> Add missing permission for release pipeline (#1767)

- config/ui-extensions/apirules-v1beta1/general
- config/ui-extensions/apirules/general
- Adjust filters for apirule v2 and v1beta1.
> Adjust filters for apirule v2 and v1beta1

- controllers/gateway/api_controller_integration_test.go
- controllers/gateway/apirule_controller.go
- tests/integration/pkg/hooks/api-gateway.go
* implement watch apirule controller to watch on service changes
* add test that checks if resource got updated
#1765
> bug: enqueue apirules reconcile on svc changes

- .github/workflows/call-pull-integration.yaml
- .github/workflows/call-ui-tests.yaml
- .github/workflows/call-verify-commit-pins.yaml
- Remove [tj-actions/changed-files](https://github.com/tj-actions/changed-files) from all pipelines.
> Remove tj-actions/changed-files

- controllers/operator/apigateway_controller.go
- controllers/operator/apigateway_controller_integration_test.go
- docs/release-notes/3.0.1.md
> [release 3.0] Enable watch for istio-ingressgateway service (#1759)

- sec-scanners-config.yaml
- Update sec scanner config for 3.0.1
> Update sec scanner config for 3.0.1

- .github/workflows/call-pull-integration.yaml
> Remove tj changed action

- .github/workflows/call-ui-tests.yaml
- .github/workflows/call-verify-commit-pins.yaml
* Remove tj-actions/changed-files
- cherry pick #1790 
> Remove tj-actions/changed-files (#1790)

- Dockerfile
- go.mod
- Sync go version in go.mod with Dockerfile, removed obsolete toolchain declaration
> Go version consistent with Dockerfile, removed obsolete toolchain declaration

- .github/actions/e2e-test-gardener/action.yaml
- .github/workflows/schedule-cleanup-garden.yaml
- hack/ci/cleanup-garden.sh
- hack/ci/shoot_aws.yaml
- hack/ci/shoot_gcp.yaml
- tests/integration/main_test.go
- Skipping environment deletion if tests failed
- Added cleanup job that cleans Gardener clusters after 2 hours
> Gardener cleanup job, disabled cluster cleanup after failed tests

- apis/operator/v1alpha1/apigateway_types.go
- controllers/gateway/ratelimit/ratelimit_controller.go
- controllers/operator/apigateway_controller.go
- Check in GetOldestApiGateway if apigateways > 0
> fix: GetOldestApiGateway assumes number of apigateways > 0

- .github/actions/k8s-compatibility-test-aws/action.yaml
- Skip Gardener cleanup also in k8s compatibility test
> Skip Gardener cleanup also in compatibility test

- config/ui-extensions/apirules-v1beta1/general
- config/ui-extensions/apirules/general
- Fix "Learn more" links for apirule 
> Fix "Learn more" links for apirule

- internal/validation/injection.go
- internal/validation/injection_test.go
- internal/validation/v2alpha1/rules.go
- internal/validation/v2alpha1/rules_test.go
- internal/validation/v2alpha1/sidecar_injection_test.go
- fix: Validate sidecar injection regardless of used handler
- https://github.com/kyma-project/api-gateway/issues/1752
> fix: Validate sidecar injection regardless of used handler

- docs/release-notes/2.11.3.md
> Add release notes for 2.11.3

- apis/gateway/v1beta1/apirule_types.go
- config/crd/bases/gateway.kyma-project.io_apirules.yaml
- includes changes to mark the `APIRule` version as deprecated and provide warnings to users. 
> fix: add deprecation warning for APIRule v1beta1 version

- docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
- docs/user/custom-resources/apirule/04-70-changes-in-apirule-v2.md
- docs/user/custom-resources/apirule/README.md
- docs/user/custom-resources/apirule/v1beta1-deprecated/04-10-apirule-custom-resource.md
- docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
- docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/README.md
- docs/user/tutorials/01-30-set-up-mtls-gateway.md
- docs/user/tutorials/01-40-expose-workload/README.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/README.md
- Update deprecation warnings for APIRules because release 3.0 has been postponed to May 5th
> Update deprecation warnings for APIRules

- .github/workflows/release-api-gateway-1.yaml
- Adjust release process so that it is able to handle cases where minor release is skipped (for example. 1.16.0 skipped in favour of 1.16.1).
- Added verification if release branch exists, if it doesn't exist it will be created.
> Improve release automation

- .github/actions/k8s-compatibility-test/action.yaml
- Test recent k8s version available on Gardener: 1.32.3
> K8s compatibility test

- .github/actions/e2e-test-k3d/action.yaml
- .github/actions/upgrade-test/action.yaml
> Bump k3s version to one compatible with latest Istio module release

- internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
- do not add istio-ingressgateway principal during migration step of ext auth rules
#1800
> bug: do not add hosts during ext auth migration

- internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
- do not add hosts and ingress gateway principal during ext auth migration
- do not add rules to the rule during migration step
- do not add istio-ingressgateway principal during migration step
#1800
> Zero downtime migration fix

- docs/user/tutorials/01-50-expose-and-secure-a-workload/01-52-expose-and-secure-workload-jwt.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/v2alpha1/01-52-expose-and-secure-workload-jwt.md
> Fix indentation in APIRules

- apis/operator/v1alpha1/apigateway_types.go
- controllers/gateway/ratelimit/ratelimit_controller.go
- controllers/operator/apigateway_controller.go
> fix: GetOldestApiGateway assumes number of apigateways > 0 

- apis/gateway/v2/apirule_conversion.go
- apis/gateway/v2/apirule_conversion_test.go
- apis/gateway/v2/path_conversion.go
- apis/gateway/v2alpha1/apirule_conversion.go
- apis/gateway/v2alpha1/apirule_conversion_test.go
- apis/gateway/v2alpha1/path_conversion.go
> feat: enhance APIRule v1beta1 conversion with original version annotations, alternative version (#1842)

- apis/gateway/v2/apirule_conversion.go
- apis/gateway/v2alpha1/apirule_conversion.go
> fix: prevent overwriting original version annotation in APIRule (#1887)

- apis/gateway/v1beta1/apirule_types.go
- config/crd/bases/gateway.kyma-project.io_apirules.yaml
- docs/release-notes/3.0.2.md
> fix: add deprecation warning for APIRule v1beta1 version (#1837)

- docs/contributor/adr/0005-api-proposal-for-configuration-of-external-authorizer-based-authorization-in-apirules.md
- docs/release-notes/3.1.0.md
- internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
- internal/processing/processors/v2alpha1/authorizationpolicy/ext_auth_test.go
- internal/processing/processors/v2alpha1/virtualservice/hosts_test.go
- internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor.go
- Add host field to the ExtAuth authorization policy
- https://github.com/kyma-project/api-gateway/issues/1844
> Add host field to ExtAuth AuthorizationPolicy

- .github/workflows/release-api-gateway-2.yaml
- Fix the way variables are passed between jobs
> Release workflow adjustments

- docs/user/_sidebar.md
> Fix link in sidebar

- .github/workflows/release-api-gateway-2.yaml
> Adjust "needs" statement

- controllers/gateway/apirule_controller.go
- Reconcile on annotation change predicate
> fix: Reconciliation on version change for convertible rule

- controllers/gateway/apirule_controller.go
> fix: Reconciliation on version change for convertible rule (#1924)

- tests/integration/pkg/resource/manager.go
- tests/integration/testsuites/upgrade/features/upgrade.feature
- tests/integration/testsuites/upgrade/scenario.go
- Added test that checks whether original-version annotation is not changed during APIGateway controller upgrade
> Tests: checking whether original-version annotation is not changed during upgrade

- config/ui-extensions/apigateways/details
- config/ui-extensions/apirules-v1beta1/dataSources
- config/ui-extensions/apirules-v1beta1/details
- config/ui-extensions/apirules-v1beta1/translations
- config/ui-extensions/apirules-v2alpha1/dataSources
- config/ui-extensions/apirules-v2alpha1/details
- config/ui-extensions/apirules/dataSources
- config/ui-extensions/apirules/details
- hack/run-ui-tests-locally-k3d.sh
- add status badge for APIGateway and APIRule.
> Add status badge.

- go.mod
- Fixed go version in go.mod (removed obsolete toolchain declaration)
> Fixed go version in go.mod

- .github/workflows/schedule-main-integration.yaml
- Added k8s compatibility tests to slack notification in schedule main job
> Added forgotten Slack notification

- docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
- docs/user/custom-resources/apirule/04-70-changes-in-apirule-v2.md
- docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
- add more descriptive example of APIRule behavior based on the way of lisitng methods in rules 
> Add example with metods to docs.

- docs/release-notes/3.1.0.md
> Release notes 3.1.0

- .github/actions/slack-notification-failed-workflow/action.yaml
- Fix slack notification attempt param
> Fix slack notification attempt param

- .github/workflows/schedule-main-integration.yaml
- Fixed wrong cloud provider in the pipeline in k8s compatibility tests
> Fixed wrong cloud provider in the pipeline

- Makefile
- Remove vet from integration tests
> Remove vet from integration tests

- .github/actions/k8s-compatibility-test/action.yaml
> tests: hack: apply git patch in compatibility tests k3d

- docs/user/custom-resources/apirule/v1beta1-deprecated/04-10-apirule-custom-resource.md
- docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
> fix broken links

- .github/workflows/post-main-integration.yaml
- .github/workflows/pull-build-push.yaml
- .github/workflows/pull-request.yaml
To enable creation of feature branches in upstream repo
> chore: enable CI on branches prefixed with feat/

- .github/workflows/post-main-integration.yaml
- .github/workflows/release-api-gateway-2.yaml
- .github/workflows/release-create-release.yaml
- Dockerfile
- Makefile
- internal/reconciliations/oathkeeper/deployment.yaml
- adapt Dockerfile
- adapt workflow of image builder
- adapt make target
> Setup for support of arm64 image building

- docs/user/apirule-migration/01-81-retrieve-v1beta1-spec.md
- docs/user/apirule-migration/01-82-migrate-allow-noop-no_auth-v1beta1-to-v2.md
- docs/user/apirule-migration/01-83-migrate-jwt-v1beta1-to-v2.md
- docs/user/apirule-migration/01-84-migrate-oauth2-v1beta1-to-v2.md
- docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
- docs/user/custom-resources/apirule/04-70-changes-in-apirule-v2.md
- docs/user/custom-resources/apirule/README.md
- docs/user/custom-resources/apirule/v1beta1-deprecated/04-10-apirule-custom-resource.md
- docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
- docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/README.md
- docs/user/tutorials/01-40-expose-workload/README.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/README.md
> Apply TW feedback to migration guides (#2046)

- config/ui-extensions/apirules-v1beta1/injections
- Updated APIRule migration banner
resolves https://github.com/orgs/kyma-project/projects/27/views/1?pane=issue&itemId=118338169&issue=kyma-project%7Capi-gateway%7C2044
> Update APIRule migration banner

- config/ui-extensions/apirules-v1beta1/injections
- Cherry-picking https://github.com/kyma-project/api-gateway/pull/2045
> Update migration banner (#2045)

- config/ui-extensions/apirules-v1beta1/details
- config/ui-extensions/apirules-v1beta1/list
- controllers/gateway/apirule_controller.go
- controllers/gateway/suite_test.go
- controllers/gateway/types.go
- internal/environment/environment.go
- internal/environment/environment_suite_test.go
- internal/environment/environment_test.go
- main.go
> [stage] Warning on v1beta1  (#1990)

- .github/workflows/call-integration-release.yaml
- .github/workflows/call-provision-btp-cluster.yaml
- .github/workflows/call-pull-integration.yaml
- .github/workflows/call-unit-lint.yaml
- .github/workflows/pull-add-bot-prs-to-project.yaml
- .github/workflows/pull-build-push.yaml
- .github/workflows/pull-request.yaml
- .github/workflows/release-api-gateway-1.yaml
- .github/workflows/release-rollout-module.yaml
- .github/workflows/schedule-ui-tests.yaml
- .github/workflows/schedule-update-sec-scanner.yaml
- Updating workflow permissions as suggested by Github Code scanning tool.
> Update Workflow permissions

- docs/release-notes/3.1.2.md
- Add release notes for migration processing
> Add release notes for migration processing

- .github/workflows/release-module-config.yaml
Adjust pipeline configuration and logic:
- No need to provide channel in this step
-  removed DEFAULT_CR_FILENAME as it is not used
- Update pipeline name and issue title as this step is associated with module release. Rollout is happening in different PR.
> Update and rename release-rollout-module.yaml 

- controllers/gateway/apirule_controller.go
(cherry picked from commit d047c735c889ccae25b4ee87919b9e6b544ba2f2)
- ...
> bug: fix assignment of LastProcessedTime field in apirule_controller.go

- docs/user/custom-resources/apigateway/04-10-kyma-gateway.md
> docs: Update links

- docs/user/apirule-migration/01-81-retrieve-v1beta1-spec.md
- docs/user/tutorials/01-40-expose-workload/v1beta1-deprecated/01-40-expose-workload-apigateway.md
- docs/user/tutorials/01-40-expose-workload/v1beta1-deprecated/01-41-expose-multiple-workloads.md
- docs/user/tutorials/01-40-expose-workload/v1beta1-deprecated/01-42-expose-workloads-multiple-namespaces.md
- docs/user/tutorials/01-40-expose-workload/v2alpha1/01-40-expose-workload-apigateway.md
- docs/user/tutorials/01-40-expose-workload/v2alpha1/01-41-expose-multiple-workloads.md
- docs/user/tutorials/01-40-expose-workload/v2alpha1/01-42-expose-workloads-multiple-namespaces.md
- docs/user/tutorials/01-40-expose-workload/v2alpha1/01-43-expose-workload-short-host-name.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/v1beta1-deprecated/01-50-expose-and-secure-workload-oauth2.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/v1beta1-deprecated/01-52-expose-and-secure-workload-jwt.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/v1beta1-deprecated/01-53-expose-and-secure-workload-istio.md
- docs/user/tutorials/01-50-expose-and-secure-a-workload/v2alpha1/01-52-expose-and-secure-workload-jwt.md
- Remove dashboard instructions for APIRules v1beta1 and v2alpha1
https://github.com/kyma-project/api-gateway/issues/2103
> Remove dashboard instructions for APIRules v1beta1 and v2alpha1

- tests/integration/testsuites/ory/features-zero-downtime-migration/zero-downtime-migration.feature
- Zero downtime tests fix - synchronized zero-downtime-migration.feature with v2alpha1_conversion.feature proper for release-3.1 branch
> Zero downtime tests fix - synchronized feature file with release-3.1 branch

- docs/release-notes/3.2.0.md
- Add deletion note for version 3.2.0
> Add deletion note for version 3.2.0

- .github/workflows/pull-request.yaml
- docs/contributor/02-10-testing-strategy.md
- Added zero-downtime migration tests to the PR flow
> Added zero-downtime migration tests to the PR flow

- .github/actions/e2e-test-gardener/action.yaml
- .github/actions/e2e-test-k3d/action.yaml
- .github/actions/provision-k3d-cluster/action.yaml
- .github/workflows/call-unit-lint.yaml
- Makefile
- hack/check_manifests_generate.sh
- hack/ci/integration-test-gardener.sh
- hack/ci/provision-gardener.sh
- tests/e2e/pkg/helpers/modules/apigateway.go
- tests/integration/main_test.go
- Add groups to provisioning
- Add check for generation
- Set flag for testfile in log
- Scale down oathkeeper in e2e-test
> Test running improvements

- .github/actions/k8s-compatibility-test/action.yaml
- Ignore endpoints in k3d compatibility test
> Ignore endpoints in k3d compatibility test

- docs/release-notes/3.1.4.md
- internal/validation/injection.go
- internal/validation/injection_test.go
> backport: Add initContainers to APIRule workload in-mesh validation (#2166)

- docs/contributor/01-20-api-gateway-dependencies.md
- Fix the link to https://gardener.cloud
> Fix the link https://gardener.cloud

- docs/contributor/01-20-api-gateway-dependencies.md
- docs/user/tutorials/01-40-expose-workload/01-42-expose-workloads-multiple-namespaces.md
- Fix tabs in multiple namespace tutorial (#2180)
> Fix tabs in multiple namespace tutorial (#2180)

- external-images.yaml
> Bump busybox image in image syncer to 1.37.0

- tests/e2e/pkg/asserts/istio/istio.go
- tests/e2e/pkg/helpers/httpincluster/curl.go
- tests/e2e/pkg/helpers/oauth2/mock/oauth2mock.go
- tests/e2e/pkg/helpers/oauth2/oauth2.go
- tests/e2e/tests/jwt/jwt_and_unrestricted.yaml
- tests/e2e/tests/jwt/jwt_apirule_issuer_jwks_not_match.yaml
- tests/e2e/tests/jwt/jwt_apirule_token_from_header.yaml
- tests/e2e/tests/jwt/jwt_apirule_token_from_param.yaml
- tests/e2e/tests/jwt/jwt_apirule_unavailable_issuer.yaml
- tests/e2e/tests/jwt/jwt_apirule_with_audience.yaml
- tests/e2e/tests/jwt/jwt_test.go
- Rewrite all tests from JWT feature file to e2e-framework 
> Rewrite JWT tests to e2e framework

- internal/processing/hashbasedstate/changes.go
- Fix print of changes from hash based state
> Fix print of changes from hash based state

- controllers/gateway/apirule_controller.go
- internal/dependencies/dependencies.go
- internal/dependencies/dependencies_test.go
- internal/processing/cleaner.go
- internal/processing/processing_test/test_utils.go
- tests/integration/pkg/hooks/api-gateway.go
- Fix Ory Rule related reconcile errors
> Fix Ory Rule related reconcile errors

- .github/actions/e2e-k3d/action.yaml
- .github/workflows/call-pull-integration.yaml
- Makefile
- tests/e2e/pkg/asserts/extauth/extauth.go
- tests/e2e/pkg/helpers/extauth/ext_auth.yaml
- tests/e2e/pkg/helpers/extauth/extauth.go
- tests/e2e/pkg/helpers/infrastructure/namespace.go
- tests/e2e/pkg/helpers/modules/istio.go
- tests/e2e/pkg/helpers/modules/operator_v1alpha2_istio_default.yaml
- tests/e2e/pkg/helpers/modules/operator_v1alpha2_istio_ext_authorizers.yaml
- tests/e2e/pkg/helpers/oauth2/mock/oauth2mock.go
- tests/e2e/pkg/helpers/oauth2/oauth2.go
- tests/e2e/pkg/helpers/testsetup/testsetup.go
- tests/e2e/tests/Makefile
- tests/e2e/tests/extauth/ext_auth_apirule.yaml
- tests/e2e/tests/extauth/ext_auth_apirule_with_jwt.yaml
- tests/e2e/tests/extauth/extauth_test.go
- tests/e2e/tests/jwt/jwt_test.go
- New implementation of e2e tests for extauth
> tests: e2e rewrite ext-auth scenario to new approach

- .github/workflows/post-main-integration.yaml
- Make post main tests to run on push to release branches
> Make post main tests to run on push to release branch 3.3

- docs/user/apirule-migration/01-85-apirule-migration-faq.md
> Apply review comments to FAQ

- apis/gateway/v2/apirule_types.go
- config/crd/bases/gateway.kyma-project.io_apirules.yaml
- docs/release-notes/3.4.0.md
- add validation check that field spec in v2 is required
- conversion check
- no double spec allowed
> Add required validation for spec in v2.
