kyma-project/api-gateway

Makefile

Set proper tag on docker image

Override tags on ci-release target

---

internal/processing/processing_test.go

- Add unit test for GetActualState
- https://github.com/kyma-project/api-gateway/issues/32

Test for fetching by label v1alpha1

---

internal/processing/processing.go
internal/processing/processing_test.go

Test for fetching by label v1alpha1
- Fetch by label v1alpha1
- Add unit test for label fetching
- https://github.com/kyma-project/api-gateway/issues/32

Patch label fetching

---

api/v1alpha1/apiRule_types.go
api/v1alpha1/groupversion_info.go
api/v1alpha1/internal_types.go
api/v1beta1/apirule_types.go
api/v1beta1/groupversion_info.go
api/v1beta1/internal_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/gateway.kyma-project.io_apirules.yaml
controllers/apirule_controller.go
internal/helpers/namespace.go
internal/processing/access_rule_helpers.go
internal/processing/helpers.go
internal/processing/processing_test.go
internal/processing/virtual_service_helpers.go
internal/validation/dummy.go
internal/validation/jwt.go
internal/validation/labels.go
internal/validation/no_config.go
internal/validation/validate.go
internal/validation/validate_test.go

Added optional `namespace` in `service` for APIRule CRD (on root `spec` or as subelement in `rules`)
Changes in this pull request:
https://github.com/kyma-project/kyma/issues/9936
https://github.com/kyma-project/api-gateway/issues/12

Add optional `namespace` for `service` in APIRule

---

cmd/cronjob/cronjob.go
config/certificates/jobs.yaml
internal/webhook/certificates.go

* Make CRD configurable so that the app can generate for different CRDs
* Adap kustomize resources to use CRD name
Make CRD configurable so that cert-handler can be configured for a different CRD too
- Make CRD configurable so that the app can generate for different CRDs
- Adap kustomize resources to use CRD name
#15346

Make Cert Handler CRD Configurable

---

Makefile
config/crd/apirules.gateway.crd.yaml
config/crd/bases/gateway.kyma-project.io_apirules.yaml

Make it easier to maintain crds in different projects
- https://github.com/kyma-project/kyma/blob/main/installation/resources/crds/api-gateway/apirules.gateway.crd.yaml

Provide make target to generate CRD with patches

---

config/configmap/configmap.yaml
config/manager/manager.yaml
config/rbac/role.yaml
controllers/api_controller_integration_test.go
controllers/api_controller_test.go
controllers/apirule_controller.go
controllers/suite_test.go
internal/builders/istio.go
internal/helpers/config.go
internal/validation/validate.go
internal/validation/validate_test.go
main.go

- default to `ory` if ConfigMap is missing
- move config validation in controller `reconcile()` before actually checking if is a new APIRule
- add watcher for the config map to APIRule controller (update event case)
- do not crash api-gateway pod, just log an error in controller logs and also set status of reconciled APIRule to error
https://github.com/kyma-project/api-gateway/issues/40

Config fail early

---

docs/API Rule performance.md

- Add performance tests results docs
- https://github.com/kyma-project/api-gateway/issues/83

Performance tests results

---

api/v1beta1/apirule_types.go

The version conversion for server-side apply of ApiRule v1alpha1 to v1beta1 failed with the error 
`The APIRule "my-rule" is invalid: spec.rules[0].service: Invalid value: "null": spec.rules[0].service in body must be of type object: "null"`
The reason for this was that the service field is defined as an object and was not set in the Go object. The default representation in JSON for an object that is not defined with omitempty is "null". This means that marshaling this object then resulted in a "null" value in the JSON, which led to an error during validation.
- Add `omitempty` JSON tag to optional Service fields
- ...
- ...
- https://github.com/kyma-project/api-gateway/issues/50

APIRule conversion failure for v1beta1 resource update on resources created in v1alpha1

---

internal/processing/istio/audience_test.go
internal/processing/istio/authorization_policy_processor.go

Istio AP validates requests based only on the first of presented JWT audiences when using `request.auth.audiences`. This doesn't cover our original Ory scenario. This however can be achieved by using `request.auth.claims[aud]`, as this will verify all JWT audiences, same as for scopes
- Change `request.auth.audiences` to `request.auth.claims[aud]`

Use aud claim instead of audiences

---

controllers/api_controller_integration_test.go
controllers/apirule_controller.go
internal/builders/virtual_service.go
internal/builders/virtual_service_test.go
internal/helpers/config.go
internal/processing/istio/virtual_service_processor.go
internal/processing/ory/virtual_service_processor.go
internal/processing/types.go

- added default http timeout value as 120s for virtual services created from an apirule
Followup Task: To make this value configurable either via configmap or through the CRD
https://github.com/kyma-project/api-gateway/issues/169

add default http timeout value for virtual services

---

tests/integration/env_vars_custom_domain.sh
tests/integration/scenario_custom_domain_test.go
tests/integration/scripts/integration-gardener-custom-domain.sh

/kind feature
/area ci
Added custom domain integration script that, much similar to standard integration script:
* provisions gardener cluster
* patches gardener shoot to enable Cert issuer extension
* Adds volatile secret to a cluster for managing DNS entries
* Install needed kyma components
* runs custom domain test
Some small changes had to be made:
* Increased factor timeout in `isDNSReady()` function to reduce flakiness of a test
* Adjusted `env_vars_custom_domain.sh` script to be aligned with `env_vars.sh` so re-using the same credentials is possible
* Had to add additional sleeps to reduce flakiness of the test, because Gardener clusters are so slow to provision and even if the APIServer is up, then not always it's possible to actually operate on a cluster

Add custom domain integration script

---

.goreleaser.yaml

Don't use default goreleaser builds.

Skip release builds

---

.github/dependabot.yml
.github/workflows/vulnerabilities-check.yaml

- Update dependabot config to ignore istio packages, since we neever used this PRs in the past. We often did it manually after the Istio module release. In the current form the PRs might stay open for very long time. Also the version might not be correct, e.g. if we skip an Istio version.
- Update go version for vulnerability check.

Update dependabot config to ignore istio packages

---

controllers/operator/apigateway_controller.go
controllers/operator/apigateway_controller_integration_test.go
controllers/operator/apigateway_controller_test.go
tests/integration/testsuites/gateway/features/kyma_gateway.feature

- Use warning status when there is more than one APIGateway CR
#879

Use warning instead of error on duplicate APIGateway CRs

---

tests/integration/scripts/custom-domain-gardener-aws-gh.sh
tests/integration/scripts/custom-domain-gardener-gcp-gh.sh

- Use proper version instead of full name
As in: https://github.com/kyma-project/cli/blob/b160f58672b18703783e0045abc91fccb8ea5580/cmd/kyma/provision/cmd.go#L9

Fix gardenlinux image version

---

controllers/operator/apigateway_controller.go
controllers/operator/apigateway_controller_test.go

/kind bug
When Oathkeeper managed rule CRDs are removed there is nothing to List in oryRuleExist function.
If that happens, ignore the error and return nil

bug: ignore NoKindMatch error in oathkeeper reconciliation

---

.github/workflows/pull-request.yaml

This reverts commit 61322abc649c3733b721f715d3a8004c22e79295.
- Revert "Bump golangci/golangci-lint-action from 4.0.0 to 5.1.0 (#1035)"

Revert "Bump golangci/golangci-lint-action from 4.0.0 to 5.1.0 (#1035)"

---

controllers/gateway/config_map.go
internal/validation/injection.go
internal/validation/injection_test.go
internal/validation/v1beta1/istio/jwt_validator_test.go
internal/validation/v2alpha1/jwt.go
internal/validation/v2alpha1/jwt_authentications_test.go
internal/validation/v2alpha1/jwt_authorizations_test.go
internal/validation/v2alpha1/jwt_test.go
internal/validation/v2alpha1/rules.go
internal/validation/v2alpha1/rules_test.go
internal/validation/v2alpha1/sidecar_injection.go
internal/validation/v2alpha1/sidecar_injection_test.go
internal/validation/v2alpha1/suite_test.go
internal/validation/v2alpha1/v2alpha1.go
internal/validation/v2alpha1/v2alpha1_test.go
main.go

- Add all relevant validation for rules from v1beta1 Istio handler including sidecar injection for v2alpha1
- Update paths from v1beta1 validation to match with new v2alpha1 APIRule
- Move tests from validation/v1beta1 package and validation/v1beta1/istio package to v2alpha1 package to verify same functionality
- Don't test against exported functions in tests, to have a smaller scoping, especially since there is another PR that will change the behaviour of the exported Validate function.
- Disable cache for v2alpha1 APIRule since this caused an issue with reconciling an APIRule that was recreated after deletion
- 

Add rules validation for v2alpha1

---

tests/integration/scripts/provision-gardener-gh.sh

/kind bug
/area ci
Seems that if API Server is not ready then endpoint will return non-200 response code. That also means kubectl will also return non-zero exit. Loop can be simplified to just check exit code and wait until its 0
See https://github.com/kyma-project/api-gateway/actions/runs/10249090704/job/28351826080#step:3:103

bug: fix premature error of kubectl get --raw /readyz

---

.github/actions/integration-tests/action.yaml
.github/actions/k8s-compatibility-test/action.yaml
.github/actions/provision-k3d-cluster/action.yaml
.github/actions/upgrade-test/action.yaml
hack/ci/custom-domain-gardener-aws.sh
hack/ci/custom-domain-gardener-gcp.sh

- bump k8s versions for int tests
- drop external gh action responsible for provisioning k3d
- provide own gh action for provisioning k3d

cicd: bump k8s versions for int tests

---

internal/reconciliations/oathkeeper/deployment.go
internal/reconciliations/oathkeeper/deployment.yaml
internal/reconciliations/oathkeeper/deployment_light.yaml

HPA needs ~30s after a workload is applied to scale it to target min replicas. Since Oathkeeper starts with 1, and the target is 3, those 30s are spend idle, as only one replica is starting, and the other two will start after HPA kicks in.
- Optimise Oathkeeper startup time by starting with replica number as in HPA config

Oathkeeper startup optimisation

---

apis/gateway/v2alpha1/apirule_conversion.go
controllers/gateway/apirule_controller.go
controllers/gateway/apirule_deletion.go
controllers/gateway/reconcile_result.go
internal/processing/reconciliation.go
internal/processing/reconciliation_test.go

/kind feature
APIRule v2alpha1 was retrieved from APIServer. This introduced unnecessary dependency to conversion webhook. So instead of asking APIServer to get resource, call ConvertTo() and ConvertFrom() directly to convert v1beta1 resource into v2alpha1.
Additionally include error in doneReconcileErrorRequeue(), because it should return an errored reconcile result.
This resolves multiple instances of error
```
2024/09/06 14:02:53 http: TLS handshake error from 10.244.0.1:57417: EOF
```
#1148

feat: replace getting converted resource in reconcile

---

.github/workflows/main-integration.yaml
.github/workflows/verify-commit-pins.yaml

/kind chore
Remove wait-for-build usage from main-integration.yaml and build directly.
#1271

chore: switch main build jobs

---

tests/ui/tests/cypress.config.ts

/kind bug
Try to mitigate recent crash of Chromium by enabling `experimentalMemoryManagement` feature, as described in Cypress documentation.

bug: enable experimentalMemoryManagement in cypress

---

docs/release-notes/2.8.0.md
internal/reconciliations/gateway/certificate.yaml

- Extend certificate key size of kyma gateway to 4096
**Additional information**
I run zero downtime test, and no downtime is present during the certificate switch

Extend certificate key size of kyma-gateway to 4096

---

hack/ci/shoot_aws.yaml
hack/ci/shoot_gcp.yaml

/kind bug
/area ci
Enable gardener control-plane HA, as described in https://gardener.cloud/docs/gardener/shoot_high_availability/

bug: enable HA control plane nodes

---

internal/builders/envoyfilter/envoyfilter.go
internal/builders/envoyfilter/envoyfilter_test.go
internal/ratelimit/ratelimit.go
internal/ratelimit/ratelimit_test.go
internal/ratelimit/testdata/envoy_patches.yaml

/kind feature
- Implement EnvoyFilterBuilder struct for easier construction of EnvoyFilter CR
- Implement LocalRateLimit package which operates on Envoy API, then builds config patches compatible with istio's EnvoyFilter API
- Add unit tests for introduced code
#1368

feat: add envoyfilter and ratelimit builders

---

hack/ci/custom-domain-gardener-aws.sh
hack/ci/custom-domain-gardener-gcp.sh
hack/ci/custom-domain-gardener.sh
hack/ci/provision-gardener.sh

- waiting for shoot provisioning in the provision-gardener script, so it finished when the cluster is fully provisioned
- waiting for shoot provisioning once again after shoot resource is patched in the custom-domain-gardener.sh, so the istio is installed on fully provisioned cluster
- waiting for the ingress gateway to be reachable via external IP before executing tests
- upgraded Gardener cluster version from 1.29.7 to 1.29.9
Randomly failing custom domain integration tests with messages like "connection reset by peer" when trying to reach httpbin endpoint.

Improved resiliency of custom domain integration tests

---

.github/workflows/pull-build-push.yaml
.github/workflows/pull-integration-release.yaml
.github/workflows/pull-integration.yaml
.github/workflows/pull-request-release.yaml
.github/workflows/pull-request.yaml
.github/workflows/pull-unit-lint.yaml
.github/workflows/ui-tests.yaml
.github/workflows/verify-commit-pins.yaml

/kind chore
/area ci
Modify usage of tj-changed files in specific files. Any kind of status other than failure is treated as `success`.
Introduce pull-request-status job that returns `success`, if all jobs return success.
This PR moves the usage of changed files filter into respective files, making the jobs in `pull-request.yaml` always reported. If any of the jobs/steps fail, the pull-request-status job will result in a failure.
This job can be used as required status check
After this PR gets merged, new status checks will have to be set:
- pull-request-status
References:
- https://github.com/orgs/community/discussions/4324#discussioncomment-3477871

hack: consolidate pull-request status into one job

---

internal/path/parser/parser.go
internal/path/segment_trie/segment_trie.go
internal/path/segment_trie/segment_trie_test.go
internal/path/token/token.go
internal/path/token/token_test.go
internal/validation/v2alpha1/rules.go
internal/validation/v2alpha1/rules_test.go

I implemented the conflict validation based on the Trie data structure.
It does two things that are not done by a regular trie:
- Nodes that are pointed to by `{**}` don't store their children, instead they store the path suffix that exists after `{**}`. Conflicts are checked by comparing the suffixes of paths with the same segments that precede `{**}`. This can be done, since the `{**}` operator must be the last in the path.
- `{*}` nodes are stored just like any other exact segment node, but are always included in conflict search.
---
- Add conflict validation to envoy template paths

Validation of path conflicts with `{**}` or `{*}` operators

---

.github/actions/integration-tests/action.yaml
.github/actions/k8s-compatibility-test/action.yaml
.github/workflows/pull-unit-lint.yaml

/kind bug
/area ci
Add exported `GITHUB_TOKEN` variable to use by install_kustomize.sh script. The script checks if variable is exported, and if it is, authenticates.
See https://github.com/kubernetes-sigs/kustomize/blob/bb7a28070905adae77c6f82b912a862de2b3a052/hack/install_kustomize.sh#L137

bug: add GITHUB_TOKEN as env variable to actions

---

.github/workflows/pull-request-release.yaml

/kind bug
/area ci
ui-tests were broken since the beginning in pull-request-release flow, because image-builder didn't export the built artifact as tar. UI tests load the image from the uploaded artifact.
Basically, after build, pull, re-tag and save the image to use it as artifact in UI tests. Kind of emulate what docker build action is doing.

bug: add export of image-builder built artifact

---

.github/workflows/create-release.yaml
.github/workflows/main-integration.yaml
.github/workflows/pull-integration-release.yaml
.github/workflows/pull-request-release.yaml
.github/workflows/ui-tests-periodic.yaml
scripts/publish_assets.sh

/kind chore
/area ci
Separate images that we run on main/releases/pr in order to keep better isolation between the artifacts to allow introducing registry automations.
#1234

chore: separate main and release images

---

config/ui-extensions/apirules/injections
config/ui-extensions/apirules/kustomization.yaml
docs/release-notes/2.10.0.md
tests/ui/tests/support/apirule.ts
tests/ui/tests/support/combobox.ts

- Add banner on v1beta1 APIRule list and APIRule details that will inform about v1beta1 deprecation
- https://github.com/kyma-project/api-gateway/issues/1423

Add APIRules v1beta1 deprecation  information in the UI

---

docs/contributor/04-10-technical-design.md
docs/release-notes/2.11.0.md
internal/reconciliations/oathkeeper/deployment.yaml
internal/reconciliations/oathkeeper/deployment_light.yaml

- Add pod antiaffinity to oathkeeper pods , schedule on different nodes and zones (HA/multi-az support)
https://github.com/kyma-project/api-gateway/issues/1171

Add pod antiaffinity to oathkeeper pods (HA/multi-az support)

---

.github/dependabot.yml

/kind chore
/area ci
Let dependabot use its default labels

chore: remove custom labels from dependabot.yml

---

tests/integration/pkg/oathkeeper/log.go
tests/integration/testsuites/gateway/scenario.go

- Add logs for Oathkeeper pods and container logs when APIGateway CR is in unexpected state during integration tests

Add Oathkeeper logs in integration tests

---

.github/actions/integration-test-gardener/action.yaml
hack/ci/custom-domain-gardener.sh

- Don't generate random names for kubeconfig to get logs in the next step

Use static kubeconfig name in github actions

---

apis/gateway/v2alpha1/apirule_types.go
internal/processing/processors/v2alpha1/reconciliation_test.go
internal/processing/processors/v2alpha1/virtualservice/regex_test.go
internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor.go
internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor_test.go
tests/integration/testsuites/v2alpha1/features/asterisk.feature

- Full support for special characters in asterisk paths
- Fix support for space in url (`%20` and `+`)

Full support for special characters in asterisk paths

---

tests/integration/scripts/test-zero-downtime.sh

- Improved zero downtime test script
- increased timeout when waiting for the URL to be available (it was the major factor of test flakiness)
- added 2 seconds delay to reduce the probability of race condition when test finishes
- added additional check whether the number of requests is too low (<10)
- more verbose logging, logging failed responses, logging the thread number, etc.

Improved zero downtime test script - increased waiting time, avoided race condition, better logging

---

controllers/gateway/ratelimit/ratelimit_disabled.go
controllers/gateway/ratelimit/ratelimit_enabled.go
controllers/operator/apigateway_controller.go
controllers/operator/apigateway_controller_integration_test.go
controllers/operator/suite_test.go

- extension of blocking deletion when RateLimit resource is present
- feature is under feature gate
#1552

feat: extend APIGateway blocking deletion with RateLimit resource

---

internal/path/segment_trie/segment_trie.go
internal/path/segment_trie/segment_trie_test.go

- Remove conflicts of path like `/abc` and `/abc/{**}`. Those should only conflict when there is a `/` at end, like `/abc/` and `/abc/{**}`

Allow for exposing of same path without "/" if already exposed using wildcard

---

internal/path/segment_trie/segment_trie.go
internal/path/segment_trie/segment_trie_test.go

- Allow for exposing of same path without "/" if already exposed using wildcard

[backport 2.10] Allow for exposing of same path without "/" if already exposed using wildcard

---

apis/gateway/ratelimit/v1alpha1/ratelimit_types.go
config/crd/bases/gateway.kyma-project.io_ratelimits.yaml
controllers/gateway/ratelimit/ratelimit_controller_integration_test.go

As defined in [ADR](https://github.com/kyma-project/api-gateway/blob/main/docs/contributor/adr/0011-rate-limit.md#usage-example), allow scenario where both `path` and `headers` can be defined for single token bucket.
Cover with controller integration tests.
> It is also possible to combine request descriptors, for example rate limit on path and headers, in the same rate limit configuration. In this case the rate limit is applied only if all specified descriptors are present in the request.
/kind bug
#1629

bug: fix bucket validation in ratelimit_types.go

---

docs/user/tutorials/01-70-rate-limit.md
docs/user/tutorials/README.md

Add rate limit tutorial that describes 3 different configurations for a workload.
* path-based
* header-based
* path and header-based
#1607

docs: ratelimit tutorials

---

tests/integration/testsuites/custom-domain/testsuite.go

- delete custom domain resources in reversed order, so the secret is still there when DNS entry is being deleted (otherwise DNS entries are not cleaned up properly)

tests: delete custom domain resources in reversed order

---

docs/release-notes/2.10.4.md
docs/release-notes/2.12.0.md
internal/builders/istio.go
internal/processing/processors/v2alpha1/authorizationpolicy/audience_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
internal/processing/processors/v2alpha1/authorizationpolicy/ext_auth_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/internal_access_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/jwt_rules_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/no_auth_rules_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/processor.go
internal/processing/processors/v2alpha1/authorizationpolicy/processor_test.go
internal/processing/processors/v2alpha1/reconciliation_test.go

- Backport `Enable internal traffic for workloads exposed by v2alpha1 APIRule`

[backport 2.10] Enable internal traffic for workloads exposed by v2alpha1 APIRule

---

docs/release-notes/2.11.1.md
docs/release-notes/2.12.0.md
internal/builders/istio.go
internal/processing/processors/v2alpha1/authorizationpolicy/audience_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
internal/processing/processors/v2alpha1/authorizationpolicy/ext_auth_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/internal_access_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/jwt_rules_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/no_auth_rules_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/processor.go
internal/processing/processors/v2alpha1/authorizationpolicy/processor_test.go
internal/processing/processors/v2alpha1/reconciliation_test.go

- Backport Enable internal traffic for workloads exposed by v2alpha1 APIRule

[backport 2.11] Enable internal traffic for workloads exposed by v2alpha1 APIRule

---

tests/integration/scripts/test-zero-downtime.sh

- enhancement call kubectl execution to rely on specific version of APIRule. This should be written like that from begining.

fix: update APIRule references in zero-downtime migration test

---

apis/operator/v1alpha1/apigateway_types.go
controllers/gateway/ratelimit/ratelimit_controller.go
controllers/gateway/ratelimit/ratelimit_controller_integration_test.go
controllers/operator/apigateway_controller.go
controllers/operator/apigateway_controller_integration_test.go
sec-scanners-config.yaml

* Enable watch for istio-ingressgateway service
* Move api gateway fetch to else
* Fix issue with re-reconcile
* Schedule api-gateway reconcile in predicate
* Delete controllers/operator/ingress_gateway_watch.go
* Add unit test
* Adjust test to check dns entry adjustment
- Cherry pick https://github.com/kyma-project/api-gateway/pull/1759

Enable watch for istio-ingressgateway service (#1759)

---

docs/release-notes/3.1.0.md
internal/builders/istio.go
internal/processing/processors/istio/authorization_policy_processor.go
internal/processing/processors/migration/processors.go
internal/processing/processors/migration/processors_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/audience_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
internal/processing/processors/v2alpha1/authorizationpolicy/ext_auth_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/jwt_rules_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/no_auth_rules_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/processor.go
internal/processing/processors/v2alpha1/authorizationpolicy/processor_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/suite_test.go
internal/processing/processors/v2alpha1/authorizationpolicy/test_builders_test.go
internal/processing/processors/v2alpha1/reconciliation.go
tests/integration/testsuites/v2/features/jwt.feature
tests/integration/testsuites/v2/scenario.go
tests/integration/testsuites/v2/scenario_initializers.go

- add host handling to authorizationPolicy
- adjust unit tests with adding a host
- copy over the code from virtualservice processor with a comment
- adjust in-cluster connectivity test to pass if in-cluster connectivity is blocked
Things that have not been changed:
- the sources for ory passthorugh APs since it's a special case during migration
- ExtAuth APs are not covered, because it requires additional work needed around lifecycle of the subresources
#1800

AuthorizationPolicy adjustments

---

apis/gateway/v2/apirule_conversion.go
apis/gateway/v2/apirule_conversion_test.go
apis/gateway/v2/path_conversion.go
apis/gateway/v2alpha1/apirule_conversion.go
apis/gateway/v2alpha1/apirule_conversion_test.go
apis/gateway/v2alpha1/path_conversion.go

To mitigate problem with race condition during update stored version and usage of data from v1beta1 API Rules introduce adding backup spec data to annotation is highly needed
**Changes proposed in this pull request:**
- save original-version annotation without converting `no_auth` and compatible `jwt`  specs to empty spec 
- introduce path compatibility check 
#1845  - this PR introduce path compatibility check

feat: enhance APIRule v1beta1 conversion with original version annotations, alternative version

---

apis/gateway/v2/apirule_conversion.go
controllers/gateway/apirule_controller.go
controllers/gateway/informers.go
controllers/gateway/suite_test.go

This PR fixing bug regarding not working service informer for v2alpha1 and v2 versions of APIRule. This was caused by empty spec in v1beta1 version. 
First occurrence was captured in integration tests on v2alpha1 stored version but increasing timeout fixed it (it was only bypassing it)
- implement service informer for v2alpha1 and v2 
- code cleanup around informer 
- reduce timeout in integration tests, checking proper behavior of informer scheduled by informer not next reconciliation

fix: introduce service informer for v2alpha1

---

tests/integration/testsuites/custom-domain/manifests/oauth-strategy.yaml
tests/integration/testsuites/upgrade/manifests/istio-jwt-common.yaml
tests/integration/testsuites/upgrade/manifests/istio-jwt-upgrade.yaml

* rewrite upgrade tests to use apirule v2 natively
* fix typo in custom-domain manifests
#1988

fix upgrade tests and resolve typo in custom-domain tests

---

controllers/gateway/apirule_controller.go
tests/integration/pkg/helpers/curl.go
tests/integration/testsuites/upgrade/scenario.go

* fix assignment of LastProcessedTime field in apirule_controller.go
* pin curl to specific version - 8.14.1 has small regression https://github.com/curl/curl/issues/17554
* adjust upgrade scenario to only use v2(alpha1)
#1988

bug: fix assignment of LastProcessedTime field in apirule_controller.go

---

.github/actions/e2e-test-k3d/action.yaml
hack/ci/integration-test-gardener.sh

Add patching to integration-test-gardener.sh.
This should resolve the validation errors in gardener int runs, the same as in K3d
#1988

tests: hack: add patch logic to gardener integration script

---

.github/workflows/post-main-integration.yaml
.github/workflows/release-api-gateway-2.yaml
.github/workflows/release-create-release.yaml

This PR removes the deprecated `build-engine: buildx` entry from workflows.

Remove build-engine: buildx

---

docs/release-notes/3.2.1.md
internal/processing/hashbasedstate/actual.go
internal/processing/hashbasedstate/authorization_policy.go
internal/processing/processors/istio/authorization_policy_processor_test.go

* Hash value of namespace into label of AuthorizationPolicy.
* Add release notes for 3.2.1
* Update AP when hash label in legacy format.
* Update docs/release-notes/3.2.1.md
* Add unit test for legacy hash label format update.
---------
- Hash value of namespace into label of AuthorizationPolicy

Hash value of namespace into label of AuthorizationPolicy. (#2167)

---

docs/user/tutorials/01-40-expose-workload/01-42-expose-workloads-multiple-namespaces.md

- Fix tabs in the tutorial [Expose Workloads in Multiple Namespaces With a Single APIRule Definition](https://kyma-project.io/#/api-gateway/user/tutorials/01-40-expose-workload/01-42-expose-workloads-multiple-namespaces?id=expose-workloads-in-multiple-namespaces-with-a-single-apirule-definition)

Fix tabs in multiple namespace tutorial

---

docs/release-notes/3.2.1.md
docs/release-notes/3.2.3.md
internal/processing/processors/request_authentication_processor.go
internal/processing/processors/v2alpha1/requestauthentication/processor.go
internal/processing/processors/v2alpha1/requestauthentication/service_selector_test.go

Cherry pick to 3.2.3 -  fix: stop using app label key to calculate desired state of RequestAuthentication
